logging:
  config: classpath:logback-spring.xml
  dir: /alidata/logs
  
mybatis:
  config: classpath:mybatis-config.xml
  
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.89.80:3306/apps?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: me2me
    password: Sp@Metro#79
    initialSize: 5
    minIdle: 5
    maxActive: 200
  redis:
    host: 192.168.89.80
    port: 6379
    database: 0
    
server:
  port: 9090
  
app:
  push:
    IOS_PUSH_ENV: dev
  live_web: https://testwebapp.me-to-me.com/ld/

im: 
  app: 
    key: c9kqb3rdcv91j
    secret: dSPWbJVHlNjrN

proxy:
  status: disable
  host: 0
  port: 0