package com.m2m.mapper;

import com.m2m.domain.AndroidCrash;
import com.m2m.domain.AndroidCrashExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AndroidCrashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    int countByExample(AndroidCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    int deleteByExample(AndroidCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    @Delete({
        "delete from android_crash",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    @Insert({
        "insert into android_crash (id, app_version, ",
        "app_build_version, device_os, ",
        "device_type, channel, ",
        "platform, created_at, ",
        "crash)",
        "values (#{id,jdbcType=BIGINT}, #{appVersion,jdbcType=VARCHAR}, ",
        "#{appBuildVersion,jdbcType=VARCHAR}, #{deviceOs,jdbcType=VARCHAR}, ",
        "#{deviceType,jdbcType=VARCHAR}, #{channel,jdbcType=VARCHAR}, ",
        "#{platform,jdbcType=VARCHAR}, #{createdAt,jdbcType=BIGINT}, ",
        "#{crash,jdbcType=LONGVARCHAR})"
    })
    int insert(AndroidCrash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    int insertSelective(AndroidCrash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    List<AndroidCrash> selectByExampleWithBLOBs(AndroidCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    List<AndroidCrash> selectByExample(AndroidCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    @Select({
        "select",
        "id, app_version, app_build_version, device_os, device_type, channel, platform, ",
        "created_at, crash",
        "from android_crash",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("ResultMapWithBLOBs")
    AndroidCrash selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") AndroidCrash record, @Param("example") AndroidCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") AndroidCrash record, @Param("example") AndroidCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    int updateByExample(@Param("record") AndroidCrash record, @Param("example") AndroidCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    int updateByPrimaryKeySelective(AndroidCrash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    @Update({
        "update android_crash",
        "set app_version = #{appVersion,jdbcType=VARCHAR},",
          "app_build_version = #{appBuildVersion,jdbcType=VARCHAR},",
          "device_os = #{deviceOs,jdbcType=VARCHAR},",
          "device_type = #{deviceType,jdbcType=VARCHAR},",
          "channel = #{channel,jdbcType=VARCHAR},",
          "platform = #{platform,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=BIGINT},",
          "crash = #{crash,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(AndroidCrash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    @Update({
        "update android_crash",
        "set app_version = #{appVersion,jdbcType=VARCHAR},",
          "app_build_version = #{appBuildVersion,jdbcType=VARCHAR},",
          "device_os = #{deviceOs,jdbcType=VARCHAR},",
          "device_type = #{deviceType,jdbcType=VARCHAR},",
          "channel = #{channel,jdbcType=VARCHAR},",
          "platform = #{platform,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AndroidCrash record);
}