package com.m2m.mapper;

import com.m2m.domain.AppDownloadLog;
import com.m2m.domain.AppDownloadLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AppDownloadLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_download_log
     *
     * @mbggenerated Wed Jan 17 14:16:55 CST 2018
     */
    int countByExample(AppDownloadLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_download_log
     *
     * @mbggenerated Wed Jan 17 14:16:55 CST 2018
     */
    int deleteByExample(AppDownloadLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_download_log
     *
     * @mbggenerated Wed Jan 17 14:16:55 CST 2018
     */
    @Delete({
        "delete from app_download_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_download_log
     *
     * @mbggenerated Wed Jan 17 14:16:55 CST 2018
     */
    @Insert({
        "insert into app_download_log (id, uid, ",
        "fromUid, create_time)",
        "values (#{id,jdbcType=INTEGER}, #{uid,jdbcType=BIGINT}, ",
        "#{fromuid,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(AppDownloadLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_download_log
     *
     * @mbggenerated Wed Jan 17 14:16:55 CST 2018
     */
    int insertSelective(AppDownloadLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_download_log
     *
     * @mbggenerated Wed Jan 17 14:16:55 CST 2018
     */
    List<AppDownloadLog> selectByExample(AppDownloadLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_download_log
     *
     * @mbggenerated Wed Jan 17 14:16:55 CST 2018
     */
    @Select({
        "select",
        "id, uid, fromUid, create_time",
        "from app_download_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    AppDownloadLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_download_log
     *
     * @mbggenerated Wed Jan 17 14:16:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") AppDownloadLog record, @Param("example") AppDownloadLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_download_log
     *
     * @mbggenerated Wed Jan 17 14:16:55 CST 2018
     */
    int updateByExample(@Param("record") AppDownloadLog record, @Param("example") AppDownloadLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_download_log
     *
     * @mbggenerated Wed Jan 17 14:16:55 CST 2018
     */
    int updateByPrimaryKeySelective(AppDownloadLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_download_log
     *
     * @mbggenerated Wed Jan 17 14:16:55 CST 2018
     */
    @Update({
        "update app_download_log",
        "set uid = #{uid,jdbcType=BIGINT},",
          "fromUid = #{fromuid,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AppDownloadLog record);
}