package com.m2m.mapper;

import com.m2m.domain.AppHttpAccess;
import com.m2m.domain.AppHttpAccessExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AppHttpAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(AppHttpAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(AppHttpAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from app_http_access",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into app_http_access (id, uid, request_uri, ",
        "request_method, start_time, ",
        "end_time, create_time, ",
        "request_params)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, #{requestUri,jdbcType=VARCHAR}, ",
        "#{requestMethod,jdbcType=VARCHAR}, #{startTime,jdbcType=BIGINT}, ",
        "#{endTime,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{requestParams,jdbcType=LONGVARCHAR})"
    })
    int insert(AppHttpAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(AppHttpAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<AppHttpAccess> selectByExampleWithBLOBs(AppHttpAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<AppHttpAccess> selectByExample(AppHttpAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, uid, request_uri, request_method, start_time, end_time, create_time, request_params",
        "from app_http_access",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("ResultMapWithBLOBs")
    AppHttpAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") AppHttpAccess record, @Param("example") AppHttpAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") AppHttpAccess record, @Param("example") AppHttpAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") AppHttpAccess record, @Param("example") AppHttpAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(AppHttpAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update app_http_access",
        "set uid = #{uid,jdbcType=BIGINT},",
          "request_uri = #{requestUri,jdbcType=VARCHAR},",
          "request_method = #{requestMethod,jdbcType=VARCHAR},",
          "start_time = #{startTime,jdbcType=BIGINT},",
          "end_time = #{endTime,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "request_params = #{requestParams,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(AppHttpAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_http_access
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update app_http_access",
        "set uid = #{uid,jdbcType=BIGINT},",
          "request_uri = #{requestUri,jdbcType=VARCHAR},",
          "request_method = #{requestMethod,jdbcType=VARCHAR},",
          "start_time = #{startTime,jdbcType=BIGINT},",
          "end_time = #{endTime,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AppHttpAccess record);
}