package com.m2m.mapper;

import com.m2m.domain.AppUiControl;
import com.m2m.domain.AppUiControlExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AppUiControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ui_control
     *
     * @mbggenerated Sat Jan 20 10:09:42 CST 2018
     */
    int countByExample(AppUiControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ui_control
     *
     * @mbggenerated Sat Jan 20 10:09:42 CST 2018
     */
    int deleteByExample(AppUiControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ui_control
     *
     * @mbggenerated Sat Jan 20 10:09:42 CST 2018
     */
    @Delete({
        "delete from app_ui_control",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ui_control
     *
     * @mbggenerated Sat Jan 20 10:09:42 CST 2018
     */
    @Insert({
        "insert into app_ui_control (id, source_code, ",
        "description, start_time, ",
        "end_time, status)",
        "values (#{id,jdbcType=BIGINT}, #{sourceCode,jdbcType=INTEGER}, ",
        "#{description,jdbcType=VARCHAR}, #{startTime,jdbcType=TIMESTAMP}, ",
        "#{endTime,jdbcType=TIMESTAMP}, #{status,jdbcType=INTEGER})"
    })
    int insert(AppUiControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ui_control
     *
     * @mbggenerated Sat Jan 20 10:09:42 CST 2018
     */
    int insertSelective(AppUiControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ui_control
     *
     * @mbggenerated Sat Jan 20 10:09:42 CST 2018
     */
    List<AppUiControl> selectByExample(AppUiControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ui_control
     *
     * @mbggenerated Sat Jan 20 10:09:42 CST 2018
     */
    @Select({
        "select",
        "id, source_code, description, start_time, end_time, status",
        "from app_ui_control",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    AppUiControl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ui_control
     *
     * @mbggenerated Sat Jan 20 10:09:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") AppUiControl record, @Param("example") AppUiControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ui_control
     *
     * @mbggenerated Sat Jan 20 10:09:42 CST 2018
     */
    int updateByExample(@Param("record") AppUiControl record, @Param("example") AppUiControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ui_control
     *
     * @mbggenerated Sat Jan 20 10:09:42 CST 2018
     */
    int updateByPrimaryKeySelective(AppUiControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ui_control
     *
     * @mbggenerated Sat Jan 20 10:09:42 CST 2018
     */
    @Update({
        "update app_ui_control",
        "set source_code = #{sourceCode,jdbcType=INTEGER},",
          "description = #{description,jdbcType=VARCHAR},",
          "start_time = #{startTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AppUiControl record);
}