package com.m2m.mapper;

import com.m2m.domain.BillboardList;
import com.m2m.domain.BillboardListExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BillboardListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_list
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(BillboardListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_list
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(BillboardListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_list
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from billboard_list",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_list
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into billboard_list (id, list_key, ",
        "target_id, type, since_id, ",
        "update_time)",
        "values (#{id,jdbcType=BIGINT}, #{listKey,jdbcType=VARCHAR}, ",
        "#{targetId,jdbcType=BIGINT}, #{type,jdbcType=INTEGER}, #{sinceId,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(BillboardList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_list
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(BillboardList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_list
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<BillboardList> selectByExample(BillboardListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_list
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, list_key, target_id, type, since_id, update_time",
        "from billboard_list",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    BillboardList selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_list
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") BillboardList record, @Param("example") BillboardListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_list
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") BillboardList record, @Param("example") BillboardListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_list
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(BillboardList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard_list
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update billboard_list",
        "set list_key = #{listKey,jdbcType=VARCHAR},",
          "target_id = #{targetId,jdbcType=BIGINT},",
          "type = #{type,jdbcType=INTEGER},",
          "since_id = #{sinceId,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BillboardList record);
}