package com.m2m.mapper;

import com.m2m.domain.BlockTopic;
import com.m2m.domain.BlockTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BlockTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_topic
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(BlockTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_topic
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(BlockTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_topic
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from block_topic",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_topic
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into block_topic (id, topic_id, ",
        "uid)",
        "values (#{id,jdbcType=INTEGER}, #{topicId,jdbcType=BIGINT}, ",
        "#{uid,jdbcType=BIGINT})"
    })
    int insert(BlockTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_topic
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(BlockTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_topic
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<BlockTopic> selectByExample(BlockTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_topic
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, topic_id, uid",
        "from block_topic",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    BlockTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_topic
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") BlockTopic record, @Param("example") BlockTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_topic
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") BlockTopic record, @Param("example") BlockTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_topic
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(BlockTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_topic
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update block_topic",
        "set topic_id = #{topicId,jdbcType=BIGINT},",
          "uid = #{uid,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BlockTopic record);
}