package com.m2m.mapper;

import com.m2m.domain.ContentTagsDetails;
import com.m2m.domain.ContentTagsDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ContentTagsDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(ContentTagsDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(ContentTagsDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from content_tags_details",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into content_tags_details (id, cid, tid, ",
        "uid, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{cid,jdbcType=BIGINT}, #{tid,jdbcType=BIGINT}, ",
        "#{uid,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(ContentTagsDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(ContentTagsDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<ContentTagsDetails> selectByExample(ContentTagsDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, cid, tid, uid, create_time",
        "from content_tags_details",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    ContentTagsDetails selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ContentTagsDetails record, @Param("example") ContentTagsDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") ContentTagsDetails record, @Param("example") ContentTagsDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(ContentTagsDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update content_tags_details",
        "set cid = #{cid,jdbcType=BIGINT},",
          "tid = #{tid,jdbcType=BIGINT},",
          "uid = #{uid,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ContentTagsDetails record);
}