package com.m2m.mapper;

import com.m2m.domain.ContentLikesDetails;
import com.m2m.domain.ContentLikesDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ContentLikesDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_likes_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(ContentLikesDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_likes_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(ContentLikesDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_likes_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from content_likes_details",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_likes_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into content_likes_details (id, cid, uid, ",
        "create_time)",
        "values (#{id,jdbcType=BIGINT}, #{cid,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(ContentLikesDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_likes_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(ContentLikesDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_likes_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<ContentLikesDetails> selectByExample(ContentLikesDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_likes_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, cid, uid, create_time",
        "from content_likes_details",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    ContentLikesDetails selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_likes_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ContentLikesDetails record, @Param("example") ContentLikesDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_likes_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") ContentLikesDetails record, @Param("example") ContentLikesDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_likes_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(ContentLikesDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_likes_details
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update content_likes_details",
        "set cid = #{cid,jdbcType=BIGINT},",
          "uid = #{uid,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ContentLikesDetails record);
}