package com.m2m.mapper;

import com.m2m.domain.ContentTags;
import com.m2m.domain.ContentTagsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ContentTagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(ContentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(ContentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from content_tags",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into content_tags (id, tag, ",
        "hot)",
        "values (#{id,jdbcType=BIGINT}, #{tag,jdbcType=VARCHAR}, ",
        "#{hot,jdbcType=INTEGER})"
    })
    int insert(ContentTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(ContentTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<ContentTags> selectByExample(ContentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, tag, hot",
        "from content_tags",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    ContentTags selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ContentTags record, @Param("example") ContentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") ContentTags record, @Param("example") ContentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(ContentTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update content_tags",
        "set tag = #{tag,jdbcType=VARCHAR},",
          "hot = #{hot,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ContentTags record);
}