package com.m2m.mapper;

import com.m2m.domain.ContentImage;
import com.m2m.domain.ContentImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ContentImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(ContentImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(ContentImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from content_image",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into content_image (id, cover, ",
        "cid, image)",
        "values (#{id,jdbcType=BIGINT}, #{cover,jdbcType=INTEGER}, ",
        "#{cid,jdbcType=BIGINT}, #{image,jdbcType=VARCHAR})"
    })
    int insert(ContentImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(ContentImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<ContentImage> selectByExample(ContentImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, cover, cid, image",
        "from content_image",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    ContentImage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ContentImage record, @Param("example") ContentImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") ContentImage record, @Param("example") ContentImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(ContentImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update content_image",
        "set cover = #{cover,jdbcType=INTEGER},",
          "cid = #{cid,jdbcType=BIGINT},",
          "image = #{image,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ContentImage record);
}