package com.m2m.mapper;

import com.m2m.domain.EmotionInfo;
import com.m2m.domain.EmotionInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface EmotionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(EmotionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(EmotionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from emotion_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into emotion_info (id, emotionName, ",
        "happyMin, happyMax, ",
        "freeMin, freeMax, ",
        "emotionPackId, topicId, ",
        "topicCoverPhoto, create_time, ",
        "status)",
        "values (#{id,jdbcType=BIGINT}, #{emotionname,jdbcType=VARCHAR}, ",
        "#{happymin,jdbcType=INTEGER}, #{happymax,jdbcType=INTEGER}, ",
        "#{freemin,jdbcType=INTEGER}, #{freemax,jdbcType=INTEGER}, ",
        "#{emotionpackid,jdbcType=BIGINT}, #{topicid,jdbcType=BIGINT}, ",
        "#{topiccoverphoto,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=INTEGER})"
    })
    int insert(EmotionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(EmotionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<EmotionInfo> selectByExample(EmotionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, emotionName, happyMin, happyMax, freeMin, freeMax, emotionPackId, topicId, ",
        "topicCoverPhoto, create_time, status",
        "from emotion_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    EmotionInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") EmotionInfo record, @Param("example") EmotionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") EmotionInfo record, @Param("example") EmotionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(EmotionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update emotion_info",
        "set emotionName = #{emotionname,jdbcType=VARCHAR},",
          "happyMin = #{happymin,jdbcType=INTEGER},",
          "happyMax = #{happymax,jdbcType=INTEGER},",
          "freeMin = #{freemin,jdbcType=INTEGER},",
          "freeMax = #{freemax,jdbcType=INTEGER},",
          "emotionPackId = #{emotionpackid,jdbcType=BIGINT},",
          "topicId = #{topicid,jdbcType=BIGINT},",
          "topicCoverPhoto = #{topiccoverphoto,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(EmotionInfo record);
}