package com.m2m.mapper;

import com.m2m.domain.GiftHistory;
import com.m2m.domain.GiftHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GiftHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_history
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(GiftHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_history
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(GiftHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_history
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from gift_history",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_history
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into gift_history (id, uid, topic_id, ",
        "gift_id, fragment_id, ",
        "gift_count, gift_price, ",
        "gift_topic_price, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, #{topicId,jdbcType=BIGINT}, ",
        "#{giftId,jdbcType=BIGINT}, #{fragmentId,jdbcType=BIGINT}, ",
        "#{giftCount,jdbcType=INTEGER}, #{giftPrice,jdbcType=INTEGER}, ",
        "#{giftTopicPrice,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(GiftHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_history
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(GiftHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_history
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<GiftHistory> selectByExample(GiftHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_history
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, uid, topic_id, gift_id, fragment_id, gift_count, gift_price, gift_topic_price, ",
        "create_time",
        "from gift_history",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    GiftHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_history
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") GiftHistory record, @Param("example") GiftHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_history
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") GiftHistory record, @Param("example") GiftHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_history
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(GiftHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_history
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update gift_history",
        "set uid = #{uid,jdbcType=BIGINT},",
          "topic_id = #{topicId,jdbcType=BIGINT},",
          "gift_id = #{giftId,jdbcType=BIGINT},",
          "fragment_id = #{fragmentId,jdbcType=BIGINT},",
          "gift_count = #{giftCount,jdbcType=INTEGER},",
          "gift_price = #{giftPrice,jdbcType=INTEGER},",
          "gift_topic_price = #{giftTopicPrice,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(GiftHistory record);
}