package com.m2m.mapper;

import com.m2m.domain.IosCrash;
import com.m2m.domain.IosCrashExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface IosCrashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    int countByExample(IosCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    int deleteByExample(IosCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    @Delete({
        "delete from ios_crash",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    @Insert({
        "insert into ios_crash (id, app_version, ",
        "app_build_version, device_os, ",
        "device_type, channel, ",
        "platform, created_at, ",
        "crash)",
        "values (#{id,jdbcType=BIGINT}, #{appVersion,jdbcType=VARCHAR}, ",
        "#{appBuildVersion,jdbcType=VARCHAR}, #{deviceOs,jdbcType=VARCHAR}, ",
        "#{deviceType,jdbcType=VARCHAR}, #{channel,jdbcType=VARCHAR}, ",
        "#{platform,jdbcType=VARCHAR}, #{createdAt,jdbcType=BIGINT}, ",
        "#{crash,jdbcType=LONGVARCHAR})"
    })
    int insert(IosCrash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    int insertSelective(IosCrash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    List<IosCrash> selectByExampleWithBLOBs(IosCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    List<IosCrash> selectByExample(IosCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    @Select({
        "select",
        "id, app_version, app_build_version, device_os, device_type, channel, platform, ",
        "created_at, crash",
        "from ios_crash",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("ResultMapWithBLOBs")
    IosCrash selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") IosCrash record, @Param("example") IosCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") IosCrash record, @Param("example") IosCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    int updateByExample(@Param("record") IosCrash record, @Param("example") IosCrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    int updateByPrimaryKeySelective(IosCrash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    @Update({
        "update ios_crash",
        "set app_version = #{appVersion,jdbcType=VARCHAR},",
          "app_build_version = #{appBuildVersion,jdbcType=VARCHAR},",
          "device_os = #{deviceOs,jdbcType=VARCHAR},",
          "device_type = #{deviceType,jdbcType=VARCHAR},",
          "channel = #{channel,jdbcType=VARCHAR},",
          "platform = #{platform,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=BIGINT},",
          "crash = #{crash,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(IosCrash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ios_crash
     *
     * @mbggenerated Fri Jan 12 17:54:48 CST 2018
     */
    @Update({
        "update ios_crash",
        "set app_version = #{appVersion,jdbcType=VARCHAR},",
          "app_build_version = #{appBuildVersion,jdbcType=VARCHAR},",
          "device_os = #{deviceOs,jdbcType=VARCHAR},",
          "device_type = #{deviceType,jdbcType=VARCHAR},",
          "channel = #{channel,jdbcType=VARCHAR},",
          "platform = #{platform,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(IosCrash record);
}