package com.m2m.mapper;

import com.m2m.domain.LotteryInfo;
import com.m2m.domain.LotteryInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface LotteryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(LotteryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(LotteryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from lottery_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into lottery_info (id, topic_id, ",
        "uid, title, summary, ",
        "win_number, create_time, ",
        "end_time, status)",
        "values (#{id,jdbcType=BIGINT}, #{topicId,jdbcType=BIGINT}, ",
        "#{uid,jdbcType=BIGINT}, #{title,jdbcType=VARCHAR}, #{summary,jdbcType=VARCHAR}, ",
        "#{winNumber,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{endTime,jdbcType=TIMESTAMP}, #{status,jdbcType=INTEGER})"
    })
    int insert(LotteryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(LotteryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<LotteryInfo> selectByExample(LotteryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, topic_id, uid, title, summary, win_number, create_time, end_time, status",
        "from lottery_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    LotteryInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") LotteryInfo record, @Param("example") LotteryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") LotteryInfo record, @Param("example") LotteryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(LotteryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update lottery_info",
        "set topic_id = #{topicId,jdbcType=BIGINT},",
          "uid = #{uid,jdbcType=BIGINT},",
          "title = #{title,jdbcType=VARCHAR},",
          "summary = #{summary,jdbcType=VARCHAR},",
          "win_number = #{winNumber,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(LotteryInfo record);
}