package com.m2m.mapper;

import com.m2m.domain.LotteryContent;
import com.m2m.domain.LotteryContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface LotteryContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    int countByExample(LotteryContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    int deleteByExample(LotteryContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    @Delete({
        "delete from lottery_content",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    @Insert({
        "insert into lottery_content (id, lottery_id, ",
        "uid, content, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{lotteryId,jdbcType=BIGINT}, ",
        "#{uid,jdbcType=BIGINT}, #{content,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(LotteryContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    int insertSelective(LotteryContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    List<LotteryContent> selectByExample(LotteryContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    @Select({
        "select",
        "id, lottery_id, uid, content, create_time",
        "from lottery_content",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    LotteryContent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") LotteryContent record, @Param("example") LotteryContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    int updateByExample(@Param("record") LotteryContent record, @Param("example") LotteryContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    int updateByPrimaryKeySelective(LotteryContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    @Update({
        "update lottery_content",
        "set lottery_id = #{lotteryId,jdbcType=BIGINT},",
          "uid = #{uid,jdbcType=BIGINT},",
          "content = #{content,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(LotteryContent record);
}