package com.m2m.mapper;

import com.m2m.domain.TeaseInfo;
import com.m2m.domain.TeaseInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TeaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tease_info
     *
     * @mbggenerated Wed Jan 17 15:41:46 CST 2018
     */
    int countByExample(TeaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tease_info
     *
     * @mbggenerated Wed Jan 17 15:41:46 CST 2018
     */
    int deleteByExample(TeaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tease_info
     *
     * @mbggenerated Wed Jan 17 15:41:46 CST 2018
     */
    @Delete({
        "delete from tease_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tease_info
     *
     * @mbggenerated Wed Jan 17 15:41:46 CST 2018
     */
    @Insert({
        "insert into tease_info (id, name, ",
        "audio, image, extra, ",
        "status, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{audio,jdbcType=VARCHAR}, #{image,jdbcType=VARCHAR}, #{extra,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(TeaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tease_info
     *
     * @mbggenerated Wed Jan 17 15:41:46 CST 2018
     */
    int insertSelective(TeaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tease_info
     *
     * @mbggenerated Wed Jan 17 15:41:46 CST 2018
     */
    List<TeaseInfo> selectByExample(TeaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tease_info
     *
     * @mbggenerated Wed Jan 17 15:41:46 CST 2018
     */
    @Select({
        "select",
        "id, name, audio, image, extra, status, create_time",
        "from tease_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    TeaseInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tease_info
     *
     * @mbggenerated Wed Jan 17 15:41:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") TeaseInfo record, @Param("example") TeaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tease_info
     *
     * @mbggenerated Wed Jan 17 15:41:46 CST 2018
     */
    int updateByExample(@Param("record") TeaseInfo record, @Param("example") TeaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tease_info
     *
     * @mbggenerated Wed Jan 17 15:41:46 CST 2018
     */
    int updateByPrimaryKeySelective(TeaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tease_info
     *
     * @mbggenerated Wed Jan 17 15:41:46 CST 2018
     */
    @Update({
        "update tease_info",
        "set name = #{name,jdbcType=VARCHAR},",
          "audio = #{audio,jdbcType=VARCHAR},",
          "image = #{image,jdbcType=VARCHAR},",
          "extra = #{extra,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TeaseInfo record);
}