package com.m2m.mapper;

import com.m2m.domain.ThirdPartUser;
import com.m2m.domain.ThirdPartUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ThirdPartUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_part_user
     *
     * @mbggenerated Mon Jan 22 09:16:53 CST 2018
     */
    int countByExample(ThirdPartUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_part_user
     *
     * @mbggenerated Mon Jan 22 09:16:53 CST 2018
     */
    int deleteByExample(ThirdPartUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_part_user
     *
     * @mbggenerated Mon Jan 22 09:16:53 CST 2018
     */
    @Delete({
        "delete from third_part_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_part_user
     *
     * @mbggenerated Mon Jan 22 09:16:53 CST 2018
     */
    @Insert({
        "insert into third_part_user (id, third_part_type, ",
        "uid, third_part_open_id, ",
        "third_part_token, third_part_unionid, ",
        "status, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=BIGINT}, #{thirdPartType,jdbcType=INTEGER}, ",
        "#{uid,jdbcType=BIGINT}, #{thirdPartOpenId,jdbcType=VARCHAR}, ",
        "#{thirdPartToken,jdbcType=VARCHAR}, #{thirdPartUnionid,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(ThirdPartUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_part_user
     *
     * @mbggenerated Mon Jan 22 09:16:53 CST 2018
     */
    int insertSelective(ThirdPartUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_part_user
     *
     * @mbggenerated Mon Jan 22 09:16:53 CST 2018
     */
    List<ThirdPartUser> selectByExample(ThirdPartUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_part_user
     *
     * @mbggenerated Mon Jan 22 09:16:53 CST 2018
     */
    @Select({
        "select",
        "id, third_part_type, uid, third_part_open_id, third_part_token, third_part_unionid, ",
        "status, create_time, update_time",
        "from third_part_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    ThirdPartUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_part_user
     *
     * @mbggenerated Mon Jan 22 09:16:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") ThirdPartUser record, @Param("example") ThirdPartUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_part_user
     *
     * @mbggenerated Mon Jan 22 09:16:53 CST 2018
     */
    int updateByExample(@Param("record") ThirdPartUser record, @Param("example") ThirdPartUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_part_user
     *
     * @mbggenerated Mon Jan 22 09:16:53 CST 2018
     */
    int updateByPrimaryKeySelective(ThirdPartUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_part_user
     *
     * @mbggenerated Mon Jan 22 09:16:53 CST 2018
     */
    @Update({
        "update third_part_user",
        "set third_part_type = #{thirdPartType,jdbcType=INTEGER},",
          "uid = #{uid,jdbcType=BIGINT},",
          "third_part_open_id = #{thirdPartOpenId,jdbcType=VARCHAR},",
          "third_part_token = #{thirdPartToken,jdbcType=VARCHAR},",
          "third_part_unionid = #{thirdPartUnionid,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ThirdPartUser record);
}