package com.m2m.mapper;

import com.m2m.domain.TopicData;
import com.m2m.domain.TopicDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TopicDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    int countByExample(TopicDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    int deleteByExample(TopicDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    @Delete({
        "delete from topic_data",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    @Insert({
        "insert into topic_data (id, topic_id, ",
        "last_price, last_price_incr, ",
        "steal_price, update_time, ",
        "diligently, approve, ",
        "update_text_length, update_text_count, ",
        "update_image_count, update_vedio_count, ",
        "update_vedio_length, update_audio_count, ",
        "update_audio_length, update_vote_count, ",
        "update_tease_count, update_day_count, ",
        "review_text_count, review_text_length, ",
        "kv0, harvest_price)",
        "values (#{id,jdbcType=BIGINT}, #{topicId,jdbcType=BIGINT}, ",
        "#{lastPrice,jdbcType=INTEGER}, #{lastPriceIncr,jdbcType=INTEGER}, ",
        "#{stealPrice,jdbcType=INTEGER}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{diligently,jdbcType=DOUBLE}, #{approve,jdbcType=DOUBLE}, ",
        "#{updateTextLength,jdbcType=INTEGER}, #{updateTextCount,jdbcType=INTEGER}, ",
        "#{updateImageCount,jdbcType=INTEGER}, #{updateVedioCount,jdbcType=INTEGER}, ",
        "#{updateVedioLength,jdbcType=INTEGER}, #{updateAudioCount,jdbcType=INTEGER}, ",
        "#{updateAudioLength,jdbcType=INTEGER}, #{updateVoteCount,jdbcType=INTEGER}, ",
        "#{updateTeaseCount,jdbcType=INTEGER}, #{updateDayCount,jdbcType=INTEGER}, ",
        "#{reviewTextCount,jdbcType=INTEGER}, #{reviewTextLength,jdbcType=INTEGER}, ",
        "#{kv0,jdbcType=INTEGER}, #{harvestPrice,jdbcType=INTEGER})"
    })
    int insert(TopicData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    int insertSelective(TopicData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    List<TopicData> selectByExample(TopicDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    @Select({
        "select",
        "id, topic_id, last_price, last_price_incr, steal_price, update_time, diligently, ",
        "approve, update_text_length, update_text_count, update_image_count, update_vedio_count, ",
        "update_vedio_length, update_audio_count, update_audio_length, update_vote_count, ",
        "update_tease_count, update_day_count, review_text_count, review_text_length, ",
        "kv0, harvest_price",
        "from topic_data",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    TopicData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") TopicData record, @Param("example") TopicDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    int updateByExample(@Param("record") TopicData record, @Param("example") TopicDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    int updateByPrimaryKeySelective(TopicData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    @Update({
        "update topic_data",
        "set topic_id = #{topicId,jdbcType=BIGINT},",
          "last_price = #{lastPrice,jdbcType=INTEGER},",
          "last_price_incr = #{lastPriceIncr,jdbcType=INTEGER},",
          "steal_price = #{stealPrice,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "diligently = #{diligently,jdbcType=DOUBLE},",
          "approve = #{approve,jdbcType=DOUBLE},",
          "update_text_length = #{updateTextLength,jdbcType=INTEGER},",
          "update_text_count = #{updateTextCount,jdbcType=INTEGER},",
          "update_image_count = #{updateImageCount,jdbcType=INTEGER},",
          "update_vedio_count = #{updateVedioCount,jdbcType=INTEGER},",
          "update_vedio_length = #{updateVedioLength,jdbcType=INTEGER},",
          "update_audio_count = #{updateAudioCount,jdbcType=INTEGER},",
          "update_audio_length = #{updateAudioLength,jdbcType=INTEGER},",
          "update_vote_count = #{updateVoteCount,jdbcType=INTEGER},",
          "update_tease_count = #{updateTeaseCount,jdbcType=INTEGER},",
          "update_day_count = #{updateDayCount,jdbcType=INTEGER},",
          "review_text_count = #{reviewTextCount,jdbcType=INTEGER},",
          "review_text_length = #{reviewTextLength,jdbcType=INTEGER},",
          "kv0 = #{kv0,jdbcType=INTEGER},",
          "harvest_price = #{harvestPrice,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TopicData record);
}