package com.m2m.mapper;

import com.m2m.domain.TopicImage;
import com.m2m.domain.TopicImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TopicImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(TopicImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(TopicImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from topic_image",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into topic_image (id, topic_id, ",
        "fid, image, create_time, ",
        "type, video_url, ",
        "like_count, extra)",
        "values (#{id,jdbcType=BIGINT}, #{topicId,jdbcType=BIGINT}, ",
        "#{fid,jdbcType=BIGINT}, #{image,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{type,jdbcType=INTEGER}, #{videoUrl,jdbcType=VARCHAR}, ",
        "#{likeCount,jdbcType=INTEGER}, #{extra,jdbcType=LONGVARCHAR})"
    })
    int insert(TopicImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(TopicImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<TopicImage> selectByExampleWithBLOBs(TopicImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<TopicImage> selectByExample(TopicImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, topic_id, fid, image, create_time, type, video_url, like_count, extra",
        "from topic_image",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("ResultMapWithBLOBs")
    TopicImage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") TopicImage record, @Param("example") TopicImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") TopicImage record, @Param("example") TopicImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") TopicImage record, @Param("example") TopicImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(TopicImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update topic_image",
        "set topic_id = #{topicId,jdbcType=BIGINT},",
          "fid = #{fid,jdbcType=BIGINT},",
          "image = #{image,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "type = #{type,jdbcType=INTEGER},",
          "video_url = #{videoUrl,jdbcType=VARCHAR},",
          "like_count = #{likeCount,jdbcType=INTEGER},",
          "extra = #{extra,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(TopicImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update topic_image",
        "set topic_id = #{topicId,jdbcType=BIGINT},",
          "fid = #{fid,jdbcType=BIGINT},",
          "image = #{image,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "type = #{type,jdbcType=INTEGER},",
          "video_url = #{videoUrl,jdbcType=VARCHAR},",
          "like_count = #{likeCount,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TopicImage record);
}