package com.m2m.mapper;

import com.m2m.domain.TopicUserConfig;
import com.m2m.domain.TopicUserConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TopicUserConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(TopicUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(TopicUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from topic_user_config",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into topic_user_config (id, uid, topic_id, ",
        "push_type, is_top)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, #{topicId,jdbcType=BIGINT}, ",
        "#{pushType,jdbcType=INTEGER}, #{isTop,jdbcType=INTEGER})"
    })
    int insert(TopicUserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(TopicUserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<TopicUserConfig> selectByExample(TopicUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, uid, topic_id, push_type, is_top",
        "from topic_user_config",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    TopicUserConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") TopicUserConfig record, @Param("example") TopicUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") TopicUserConfig record, @Param("example") TopicUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(TopicUserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update topic_user_config",
        "set uid = #{uid,jdbcType=BIGINT},",
          "topic_id = #{topicId,jdbcType=BIGINT},",
          "push_type = #{pushType,jdbcType=INTEGER},",
          "is_top = #{isTop,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TopicUserConfig record);
}