package com.m2m.mapper;

import com.m2m.domain.TopicReadHis;
import com.m2m.domain.TopicReadHisExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TopicReadHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_read_his
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(TopicReadHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_read_his
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(TopicReadHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_read_his
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from topic_read_his",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_read_his
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into topic_read_his (id, uid, topic_id, ",
        "read_count, read_count_dummy, ",
        "in_app, from_uid, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, #{topicId,jdbcType=BIGINT}, ",
        "#{readCount,jdbcType=INTEGER}, #{readCountDummy,jdbcType=INTEGER}, ",
        "#{inApp,jdbcType=INTEGER}, #{fromUid,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(TopicReadHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_read_his
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(TopicReadHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_read_his
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<TopicReadHis> selectByExample(TopicReadHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_read_his
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, uid, topic_id, read_count, read_count_dummy, in_app, from_uid, create_time",
        "from topic_read_his",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    TopicReadHis selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_read_his
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") TopicReadHis record, @Param("example") TopicReadHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_read_his
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") TopicReadHis record, @Param("example") TopicReadHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_read_his
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(TopicReadHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_read_his
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update topic_read_his",
        "set uid = #{uid,jdbcType=BIGINT},",
          "topic_id = #{topicId,jdbcType=BIGINT},",
          "read_count = #{readCount,jdbcType=INTEGER},",
          "read_count_dummy = #{readCountDummy,jdbcType=INTEGER},",
          "in_app = #{inApp,jdbcType=INTEGER},",
          "from_uid = #{fromUid,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TopicReadHis record);
}