package com.m2m.mapper;

import com.m2m.domain.TopicUserForbid;
import com.m2m.domain.TopicUserForbidExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TopicUserForbidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_forbid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(TopicUserForbidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_forbid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(TopicUserForbidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_forbid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from topic_user_forbid",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_forbid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into topic_user_forbid (id, topic_id, ",
        "uid, forbid_pattern, ",
        "opt_uid, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{topicId,jdbcType=BIGINT}, ",
        "#{uid,jdbcType=BIGINT}, #{forbidPattern,jdbcType=INTEGER}, ",
        "#{optUid,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(TopicUserForbid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_forbid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(TopicUserForbid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_forbid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<TopicUserForbid> selectByExample(TopicUserForbidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_forbid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, topic_id, uid, forbid_pattern, opt_uid, create_time",
        "from topic_user_forbid",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    TopicUserForbid selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_forbid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") TopicUserForbid record, @Param("example") TopicUserForbidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_forbid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") TopicUserForbid record, @Param("example") TopicUserForbidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_forbid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(TopicUserForbid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user_forbid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update topic_user_forbid",
        "set topic_id = #{topicId,jdbcType=BIGINT},",
          "uid = #{uid,jdbcType=BIGINT},",
          "forbid_pattern = #{forbidPattern,jdbcType=INTEGER},",
          "opt_uid = #{optUid,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TopicUserForbid record);
}