package com.m2m.mapper;

import com.m2m.domain.TopicBadTag;
import com.m2m.domain.TopicBadTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TopicBadTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_bad_tag
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(TopicBadTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_bad_tag
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(TopicBadTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_bad_tag
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from topic_bad_tag",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_bad_tag
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into topic_bad_tag (id, topic_id, ",
        "reporter_uid, create_time, ",
        "tag)",
        "values (#{id,jdbcType=INTEGER}, #{topicId,jdbcType=BIGINT}, ",
        "#{reporterUid,jdbcType=BIGINT}, #{createTime,jdbcType=DATE}, ",
        "#{tag,jdbcType=VARCHAR})"
    })
    int insert(TopicBadTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_bad_tag
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(TopicBadTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_bad_tag
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<TopicBadTag> selectByExample(TopicBadTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_bad_tag
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, topic_id, reporter_uid, create_time, tag",
        "from topic_bad_tag",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TopicBadTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_bad_tag
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") TopicBadTag record, @Param("example") TopicBadTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_bad_tag
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") TopicBadTag record, @Param("example") TopicBadTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_bad_tag
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(TopicBadTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_bad_tag
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update topic_bad_tag",
        "set topic_id = #{topicId,jdbcType=BIGINT},",
          "reporter_uid = #{reporterUid,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=DATE},",
          "tag = #{tag,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TopicBadTag record);
}