package com.m2m.mapper;

import com.m2m.domain.TopicGiven;
import com.m2m.domain.TopicGivenExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TopicGivenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_given
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(TopicGivenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_given
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(TopicGivenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_given
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from topic_given",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_given
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into topic_given (id, uid, ",
        "cover, title, summary, ",
        "tags, sub_type, create_time)",
        "values (#{id,jdbcType=INTEGER}, #{uid,jdbcType=INTEGER}, ",
        "#{cover,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, #{summary,jdbcType=VARCHAR}, ",
        "#{tags,jdbcType=VARCHAR}, #{subType,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(TopicGiven record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_given
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(TopicGiven record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_given
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<TopicGiven> selectByExample(TopicGivenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_given
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, uid, cover, title, summary, tags, sub_type, create_time",
        "from topic_given",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TopicGiven selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_given
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") TopicGiven record, @Param("example") TopicGivenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_given
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") TopicGiven record, @Param("example") TopicGivenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_given
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(TopicGiven record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_given
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update topic_given",
        "set uid = #{uid,jdbcType=INTEGER},",
          "cover = #{cover,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "summary = #{summary,jdbcType=VARCHAR},",
          "tags = #{tags,jdbcType=VARCHAR},",
          "sub_type = #{subType,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TopicGiven record);
}