package com.m2m.mapper;

import com.m2m.domain.TopicFragmentTemplate;
import com.m2m.domain.TopicFragmentTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TopicFragmentTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment_template
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(TopicFragmentTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment_template
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(TopicFragmentTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment_template
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from topic_fragment_template",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment_template
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into topic_fragment_template (id, type, ",
        "content, contentType)",
        "values (#{id,jdbcType=BIGINT}, #{type,jdbcType=INTEGER}, ",
        "#{content,jdbcType=VARCHAR}, #{contenttype,jdbcType=INTEGER})"
    })
    int insert(TopicFragmentTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment_template
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(TopicFragmentTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment_template
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<TopicFragmentTemplate> selectByExample(TopicFragmentTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment_template
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, type, content, contentType",
        "from topic_fragment_template",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    TopicFragmentTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment_template
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") TopicFragmentTemplate record, @Param("example") TopicFragmentTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment_template
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") TopicFragmentTemplate record, @Param("example") TopicFragmentTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment_template
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(TopicFragmentTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_fragment_template
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update topic_fragment_template",
        "set type = #{type,jdbcType=INTEGER},",
          "content = #{content,jdbcType=VARCHAR},",
          "contentType = #{contenttype,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TopicFragmentTemplate record);
}