package com.m2m.mapper;

import com.m2m.domain.UserFriendReclist;
import com.m2m.domain.UserFriendReclistExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserFriendReclistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_reclist
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(UserFriendReclistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_reclist
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(UserFriendReclistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_reclist
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from user_friend_reclist",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_reclist
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into user_friend_reclist (id, uid, rec_uid, ",
        "description, create_time, ",
        "status)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, #{recUid,jdbcType=BIGINT}, ",
        "#{description,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=INTEGER})"
    })
    int insert(UserFriendReclist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_reclist
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(UserFriendReclist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_reclist
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<UserFriendReclist> selectByExample(UserFriendReclistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_reclist
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, uid, rec_uid, description, create_time, status",
        "from user_friend_reclist",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    UserFriendReclist selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_reclist
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserFriendReclist record, @Param("example") UserFriendReclistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_reclist
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") UserFriendReclist record, @Param("example") UserFriendReclistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_reclist
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(UserFriendReclist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_reclist
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update user_friend_reclist",
        "set uid = #{uid,jdbcType=BIGINT},",
          "rec_uid = #{recUid,jdbcType=BIGINT},",
          "description = #{description,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserFriendReclist record);
}