package com.m2m.mapper;

import com.m2m.domain.UserStealLog;
import com.m2m.domain.UserStealLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserStealLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(UserStealLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(UserStealLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from user_steal_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into user_steal_log (id, uid, ",
        "topic_id, stealed_coins, ",
        "create_time, is_big_red_pack)",
        "values (#{id,jdbcType=INTEGER}, #{uid,jdbcType=BIGINT}, ",
        "#{topicId,jdbcType=BIGINT}, #{stealedCoins,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{isBigRedPack,jdbcType=INTEGER})"
    })
    int insert(UserStealLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(UserStealLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<UserStealLog> selectByExample(UserStealLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, uid, topic_id, stealed_coins, create_time, is_big_red_pack",
        "from user_steal_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    UserStealLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserStealLog record, @Param("example") UserStealLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") UserStealLog record, @Param("example") UserStealLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(UserStealLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update user_steal_log",
        "set uid = #{uid,jdbcType=BIGINT},",
          "topic_id = #{topicId,jdbcType=BIGINT},",
          "stealed_coins = #{stealedCoins,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_big_red_pack = #{isBigRedPack,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserStealLog record);
}