package com.m2m.mapper;

import com.m2m.domain.UserFriendApply;
import com.m2m.domain.UserFriendApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserFriendApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_apply
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    int countByExample(UserFriendApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_apply
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    int deleteByExample(UserFriendApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_apply
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    @Delete({
        "delete from user_friend_apply",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_apply
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    @Insert({
        "insert into user_friend_apply (id, source_uid, ",
        "target_uid, from_uid, ",
        "content, create_time, ",
        "update_time, status)",
        "values (#{id,jdbcType=BIGINT}, #{sourceUid,jdbcType=BIGINT}, ",
        "#{targetUid,jdbcType=BIGINT}, #{fromUid,jdbcType=BIGINT}, ",
        "#{content,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{status,jdbcType=INTEGER})"
    })
    int insert(UserFriendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_apply
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    int insertSelective(UserFriendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_apply
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    List<UserFriendApply> selectByExample(UserFriendApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_apply
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    @Select({
        "select",
        "id, source_uid, target_uid, from_uid, content, create_time, update_time, status",
        "from user_friend_apply",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    UserFriendApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_apply
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserFriendApply record, @Param("example") UserFriendApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_apply
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    int updateByExample(@Param("record") UserFriendApply record, @Param("example") UserFriendApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_apply
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    int updateByPrimaryKeySelective(UserFriendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_apply
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    @Update({
        "update user_friend_apply",
        "set source_uid = #{sourceUid,jdbcType=BIGINT},",
          "target_uid = #{targetUid,jdbcType=BIGINT},",
          "from_uid = #{fromUid,jdbcType=BIGINT},",
          "content = #{content,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserFriendApply record);
}