package com.m2m.mapper;

import com.m2m.domain.UserIndustryWrong;
import com.m2m.domain.UserIndustryWrongExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserIndustryWrongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry_wrong
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(UserIndustryWrongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry_wrong
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(UserIndustryWrongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry_wrong
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from user_industry_wrong",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry_wrong
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into user_industry_wrong (id, uid, industry_id, ",
        "create_time)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, #{industryId,jdbcType=BIGINT}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(UserIndustryWrong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry_wrong
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(UserIndustryWrong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry_wrong
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<UserIndustryWrong> selectByExample(UserIndustryWrongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry_wrong
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, uid, industry_id, create_time",
        "from user_industry_wrong",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    UserIndustryWrong selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry_wrong
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserIndustryWrong record, @Param("example") UserIndustryWrongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry_wrong
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") UserIndustryWrong record, @Param("example") UserIndustryWrongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry_wrong
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(UserIndustryWrong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_industry_wrong
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update user_industry_wrong",
        "set uid = #{uid,jdbcType=BIGINT},",
          "industry_id = #{industryId,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserIndustryWrong record);
}