package com.m2m.mapper;

import com.m2m.domain.UserFriend;
import com.m2m.domain.UserFriendExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    int countByExample(UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    int deleteByExample(UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    @Delete({
        "delete from user_friend",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    @Insert({
        "insert into user_friend (id, source_uid, ",
        "target_uid, from_uid, ",
        "silence_time, create_time, ",
        "status)",
        "values (#{id,jdbcType=BIGINT}, #{sourceUid,jdbcType=BIGINT}, ",
        "#{targetUid,jdbcType=BIGINT}, #{fromUid,jdbcType=BIGINT}, ",
        "#{silenceTime,jdbcType=TIMESTAMP}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=INTEGER})"
    })
    int insert(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    int insertSelective(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    List<UserFriend> selectByExample(UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    @Select({
        "select",
        "id, source_uid, target_uid, from_uid, silence_time, create_time, status",
        "from user_friend",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    UserFriend selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserFriend record, @Param("example") UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    int updateByExample(@Param("record") UserFriend record, @Param("example") UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    int updateByPrimaryKeySelective(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbggenerated Fri Jan 12 15:07:49 CST 2018
     */
    @Update({
        "update user_friend",
        "set source_uid = #{sourceUid,jdbcType=BIGINT},",
          "target_uid = #{targetUid,jdbcType=BIGINT},",
          "from_uid = #{fromUid,jdbcType=BIGINT},",
          "silence_time = #{silenceTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserFriend record);
}