package com.m2m.mapper;

import com.m2m.domain.UserLastChannel;
import com.m2m.domain.UserLastChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserLastChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_last_channel
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(UserLastChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_last_channel
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(UserLastChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_last_channel
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from user_last_channel",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_last_channel
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into user_last_channel (id, uid, channel, ",
        "login_time, device_token)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, #{channel,jdbcType=VARCHAR}, ",
        "#{loginTime,jdbcType=TIMESTAMP}, #{deviceToken,jdbcType=VARCHAR})"
    })
    int insert(UserLastChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_last_channel
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(UserLastChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_last_channel
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<UserLastChannel> selectByExample(UserLastChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_last_channel
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, uid, channel, login_time, device_token",
        "from user_last_channel",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    UserLastChannel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_last_channel
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserLastChannel record, @Param("example") UserLastChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_last_channel
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") UserLastChannel record, @Param("example") UserLastChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_last_channel
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(UserLastChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_last_channel
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update user_last_channel",
        "set uid = #{uid,jdbcType=BIGINT},",
          "channel = #{channel,jdbcType=VARCHAR},",
          "login_time = #{loginTime,jdbcType=TIMESTAMP},",
          "device_token = #{deviceToken,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserLastChannel record);
}