package com.m2m.mapper;

import com.m2m.domain.UserNoticeUnread;
import com.m2m.domain.UserNoticeUnreadExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserNoticeUnreadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(UserNoticeUnreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(UserNoticeUnreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from user_notice_unread",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into user_notice_unread (id, uid, create_time, ",
        "notice_id, level, ",
        "notice_type, content_type, ",
        "cid)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{noticeId,jdbcType=BIGINT}, #{level,jdbcType=INTEGER}, ",
        "#{noticeType,jdbcType=INTEGER}, #{contentType,jdbcType=INTEGER}, ",
        "#{cid,jdbcType=BIGINT})"
    })
    int insert(UserNoticeUnread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(UserNoticeUnread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<UserNoticeUnread> selectByExample(UserNoticeUnreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, uid, create_time, notice_id, level, notice_type, content_type, cid",
        "from user_notice_unread",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    UserNoticeUnread selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserNoticeUnread record, @Param("example") UserNoticeUnreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") UserNoticeUnread record, @Param("example") UserNoticeUnreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(UserNoticeUnread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update user_notice_unread",
        "set uid = #{uid,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "notice_id = #{noticeId,jdbcType=BIGINT},",
          "level = #{level,jdbcType=INTEGER},",
          "notice_type = #{noticeType,jdbcType=INTEGER},",
          "content_type = #{contentType,jdbcType=INTEGER},",
          "cid = #{cid,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserNoticeUnread record);
}