package com.m2m.mapper;

import com.m2m.domain.UserNotice;
import com.m2m.domain.UserNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(UserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(UserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from user_notice",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into user_notice (id, notice_type, ",
        "from_uid, to_uid, from_nick_name, ",
        "to_nick_name, tag, ",
        "cover_image, summary, ",
        "like_count, from_avatar, ",
        "push_status, read_status, ",
        "cid, create_time, ",
        "extra, review)",
        "values (#{id,jdbcType=BIGINT}, #{noticeType,jdbcType=INTEGER}, ",
        "#{fromUid,jdbcType=BIGINT}, #{toUid,jdbcType=BIGINT}, #{fromNickName,jdbcType=VARCHAR}, ",
        "#{toNickName,jdbcType=VARCHAR}, #{tag,jdbcType=VARCHAR}, ",
        "#{coverImage,jdbcType=VARCHAR}, #{summary,jdbcType=VARCHAR}, ",
        "#{likeCount,jdbcType=INTEGER}, #{fromAvatar,jdbcType=VARCHAR}, ",
        "#{pushStatus,jdbcType=INTEGER}, #{readStatus,jdbcType=INTEGER}, ",
        "#{cid,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{extra,jdbcType=VARCHAR}, #{review,jdbcType=LONGVARCHAR})"
    })
    int insert(UserNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(UserNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<UserNotice> selectByExampleWithBLOBs(UserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<UserNotice> selectByExample(UserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, notice_type, from_uid, to_uid, from_nick_name, to_nick_name, tag, cover_image, ",
        "summary, like_count, from_avatar, push_status, read_status, cid, create_time, ",
        "extra, review",
        "from user_notice",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("ResultMapWithBLOBs")
    UserNotice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserNotice record, @Param("example") UserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") UserNotice record, @Param("example") UserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") UserNotice record, @Param("example") UserNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(UserNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update user_notice",
        "set notice_type = #{noticeType,jdbcType=INTEGER},",
          "from_uid = #{fromUid,jdbcType=BIGINT},",
          "to_uid = #{toUid,jdbcType=BIGINT},",
          "from_nick_name = #{fromNickName,jdbcType=VARCHAR},",
          "to_nick_name = #{toNickName,jdbcType=VARCHAR},",
          "tag = #{tag,jdbcType=VARCHAR},",
          "cover_image = #{coverImage,jdbcType=VARCHAR},",
          "summary = #{summary,jdbcType=VARCHAR},",
          "like_count = #{likeCount,jdbcType=INTEGER},",
          "from_avatar = #{fromAvatar,jdbcType=VARCHAR},",
          "push_status = #{pushStatus,jdbcType=INTEGER},",
          "read_status = #{readStatus,jdbcType=INTEGER},",
          "cid = #{cid,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "extra = #{extra,jdbcType=VARCHAR},",
          "review = #{review,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(UserNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update user_notice",
        "set notice_type = #{noticeType,jdbcType=INTEGER},",
          "from_uid = #{fromUid,jdbcType=BIGINT},",
          "to_uid = #{toUid,jdbcType=BIGINT},",
          "from_nick_name = #{fromNickName,jdbcType=VARCHAR},",
          "to_nick_name = #{toNickName,jdbcType=VARCHAR},",
          "tag = #{tag,jdbcType=VARCHAR},",
          "cover_image = #{coverImage,jdbcType=VARCHAR},",
          "summary = #{summary,jdbcType=VARCHAR},",
          "like_count = #{likeCount,jdbcType=INTEGER},",
          "from_avatar = #{fromAvatar,jdbcType=VARCHAR},",
          "push_status = #{pushStatus,jdbcType=INTEGER},",
          "read_status = #{readStatus,jdbcType=INTEGER},",
          "cid = #{cid,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "extra = #{extra,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserNotice record);
}