package com.m2m.mapper;

import com.m2m.domain.UserHobby;
import com.m2m.domain.UserHobbyExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserHobbyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(UserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(UserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from user_hobby",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into user_hobby (id, uid, hobby)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, #{hobby,jdbcType=BIGINT})"
    })
    int insert(UserHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(UserHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<UserHobby> selectByExample(UserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, uid, hobby",
        "from user_hobby",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    UserHobby selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserHobby record, @Param("example") UserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") UserHobby record, @Param("example") UserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(UserHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update user_hobby",
        "set uid = #{uid,jdbcType=BIGINT},",
          "hobby = #{hobby,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserHobby record);
}