package com.m2m.mapper;

import com.m2m.domain.UserFriendHis;
import com.m2m.domain.UserFriendHisExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserFriendHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_his
     *
     * @mbggenerated Thu Jan 11 14:53:24 CST 2018
     */
    int countByExample(UserFriendHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_his
     *
     * @mbggenerated Thu Jan 11 14:53:24 CST 2018
     */
    int deleteByExample(UserFriendHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_his
     *
     * @mbggenerated Thu Jan 11 14:53:24 CST 2018
     */
    @Delete({
        "delete from user_friend_his",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_his
     *
     * @mbggenerated Thu Jan 11 14:53:24 CST 2018
     */
    @Insert({
        "insert into user_friend_his (id, source_uid, ",
        "target_uid, from_uid, ",
        "type, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{sourceUid,jdbcType=BIGINT}, ",
        "#{targetUid,jdbcType=BIGINT}, #{fromUid,jdbcType=BIGINT}, ",
        "#{type,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(UserFriendHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_his
     *
     * @mbggenerated Thu Jan 11 14:53:24 CST 2018
     */
    int insertSelective(UserFriendHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_his
     *
     * @mbggenerated Thu Jan 11 14:53:24 CST 2018
     */
    List<UserFriendHis> selectByExample(UserFriendHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_his
     *
     * @mbggenerated Thu Jan 11 14:53:24 CST 2018
     */
    @Select({
        "select",
        "id, source_uid, target_uid, from_uid, type, create_time",
        "from user_friend_his",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    UserFriendHis selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_his
     *
     * @mbggenerated Thu Jan 11 14:53:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserFriendHis record, @Param("example") UserFriendHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_his
     *
     * @mbggenerated Thu Jan 11 14:53:24 CST 2018
     */
    int updateByExample(@Param("record") UserFriendHis record, @Param("example") UserFriendHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_his
     *
     * @mbggenerated Thu Jan 11 14:53:24 CST 2018
     */
    int updateByPrimaryKeySelective(UserFriendHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend_his
     *
     * @mbggenerated Thu Jan 11 14:53:24 CST 2018
     */
    @Update({
        "update user_friend_his",
        "set source_uid = #{sourceUid,jdbcType=BIGINT},",
          "target_uid = #{targetUid,jdbcType=BIGINT},",
          "from_uid = #{fromUid,jdbcType=BIGINT},",
          "type = #{type,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserFriendHis record);
}