package com.m2m.mapper;

import com.m2m.domain.UserVisitLog;
import com.m2m.domain.UserVisitLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserVisitLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_visit_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int countByExample(UserVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_visit_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int deleteByExample(UserVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_visit_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Delete({
        "delete from user_visit_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_visit_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Insert({
        "insert into user_visit_log (id, action, ",
        "uid, topic_id, extra, ",
        "create_time)",
        "values (#{id,jdbcType=BIGINT}, #{action,jdbcType=VARCHAR}, ",
        "#{uid,jdbcType=BIGINT}, #{topicId,jdbcType=BIGINT}, #{extra,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(UserVisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_visit_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int insertSelective(UserVisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_visit_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    List<UserVisitLog> selectByExample(UserVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_visit_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Select({
        "select",
        "id, action, uid, topic_id, extra, create_time",
        "from user_visit_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    UserVisitLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_visit_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserVisitLog record, @Param("example") UserVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_visit_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByExample(@Param("record") UserVisitLog record, @Param("example") UserVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_visit_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(UserVisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_visit_log
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    @Update({
        "update user_visit_log",
        "set action = #{action,jdbcType=VARCHAR},",
          "uid = #{uid,jdbcType=BIGINT},",
          "topic_id = #{topicId,jdbcType=BIGINT},",
          "extra = #{extra,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserVisitLog record);
}