package com.m2m.mapper;

import com.m2m.domain.UserFamous;
import com.m2m.domain.UserFamousExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserFamousMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_famous
     *
     * @mbggenerated Thu Jan 11 16:50:54 CST 2018
     */
    int countByExample(UserFamousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_famous
     *
     * @mbggenerated Thu Jan 11 16:50:54 CST 2018
     */
    int deleteByExample(UserFamousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_famous
     *
     * @mbggenerated Thu Jan 11 16:50:54 CST 2018
     */
    @Delete({
        "delete from user_famous",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_famous
     *
     * @mbggenerated Thu Jan 11 16:50:54 CST 2018
     */
    @Insert({
        "insert into user_famous (id, uid, update_time)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(UserFamous record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_famous
     *
     * @mbggenerated Thu Jan 11 16:50:54 CST 2018
     */
    int insertSelective(UserFamous record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_famous
     *
     * @mbggenerated Thu Jan 11 16:50:54 CST 2018
     */
    List<UserFamous> selectByExample(UserFamousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_famous
     *
     * @mbggenerated Thu Jan 11 16:50:54 CST 2018
     */
    @Select({
        "select",
        "id, uid, update_time",
        "from user_famous",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    UserFamous selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_famous
     *
     * @mbggenerated Thu Jan 11 16:50:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserFamous record, @Param("example") UserFamousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_famous
     *
     * @mbggenerated Thu Jan 11 16:50:54 CST 2018
     */
    int updateByExample(@Param("record") UserFamous record, @Param("example") UserFamousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_famous
     *
     * @mbggenerated Thu Jan 11 16:50:54 CST 2018
     */
    int updateByPrimaryKeySelective(UserFamous record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_famous
     *
     * @mbggenerated Thu Jan 11 16:50:54 CST 2018
     */
    @Update({
        "update user_famous",
        "set uid = #{uid,jdbcType=BIGINT},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserFamous record);
}