package com.m2m.mapper;

import com.m2m.domain.VersionChannelDownload;
import com.m2m.domain.VersionChannelDownloadExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface VersionChannelDownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_channel_download
     *
     * @mbggenerated Sat Jan 20 10:21:26 CST 2018
     */
    int countByExample(VersionChannelDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_channel_download
     *
     * @mbggenerated Sat Jan 20 10:21:26 CST 2018
     */
    int deleteByExample(VersionChannelDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_channel_download
     *
     * @mbggenerated Sat Jan 20 10:21:26 CST 2018
     */
    @Delete({
        "delete from version_channel_download",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_channel_download
     *
     * @mbggenerated Sat Jan 20 10:21:26 CST 2018
     */
    @Insert({
        "insert into version_channel_download (id, channel, ",
        "type, version_addr, ",
        "update_time)",
        "values (#{id,jdbcType=BIGINT}, #{channel,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=INTEGER}, #{versionAddr,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(VersionChannelDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_channel_download
     *
     * @mbggenerated Sat Jan 20 10:21:26 CST 2018
     */
    int insertSelective(VersionChannelDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_channel_download
     *
     * @mbggenerated Sat Jan 20 10:21:26 CST 2018
     */
    List<VersionChannelDownload> selectByExample(VersionChannelDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_channel_download
     *
     * @mbggenerated Sat Jan 20 10:21:26 CST 2018
     */
    @Select({
        "select",
        "id, channel, type, version_addr, update_time",
        "from version_channel_download",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    VersionChannelDownload selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_channel_download
     *
     * @mbggenerated Sat Jan 20 10:21:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") VersionChannelDownload record, @Param("example") VersionChannelDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_channel_download
     *
     * @mbggenerated Sat Jan 20 10:21:26 CST 2018
     */
    int updateByExample(@Param("record") VersionChannelDownload record, @Param("example") VersionChannelDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_channel_download
     *
     * @mbggenerated Sat Jan 20 10:21:26 CST 2018
     */
    int updateByPrimaryKeySelective(VersionChannelDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_channel_download
     *
     * @mbggenerated Sat Jan 20 10:21:26 CST 2018
     */
    @Update({
        "update version_channel_download",
        "set channel = #{channel,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "version_addr = #{versionAddr,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(VersionChannelDownload record);
}