package com.m2m.mapper;

import com.m2m.domain.VersionControl;
import com.m2m.domain.VersionControlExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface VersionControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated Sat Jan 20 10:15:32 CST 2018
     */
    int countByExample(VersionControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated Sat Jan 20 10:15:32 CST 2018
     */
    int deleteByExample(VersionControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated Sat Jan 20 10:15:32 CST 2018
     */
    @Delete({
        "delete from version_control",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated Sat Jan 20 10:15:32 CST 2018
     */
    @Insert({
        "insert into version_control (id, version, ",
        "platform, update_description, ",
        "update_url, force_update, ",
        "update_time)",
        "values (#{id,jdbcType=BIGINT}, #{version,jdbcType=VARCHAR}, ",
        "#{platform,jdbcType=INTEGER}, #{updateDescription,jdbcType=VARCHAR}, ",
        "#{updateUrl,jdbcType=VARCHAR}, #{forceUpdate,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(VersionControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated Sat Jan 20 10:15:32 CST 2018
     */
    int insertSelective(VersionControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated Sat Jan 20 10:15:32 CST 2018
     */
    List<VersionControl> selectByExample(VersionControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated Sat Jan 20 10:15:32 CST 2018
     */
    @Select({
        "select",
        "id, version, platform, update_description, update_url, force_update, update_time",
        "from version_control",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    VersionControl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated Sat Jan 20 10:15:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") VersionControl record, @Param("example") VersionControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated Sat Jan 20 10:15:32 CST 2018
     */
    int updateByExample(@Param("record") VersionControl record, @Param("example") VersionControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated Sat Jan 20 10:15:32 CST 2018
     */
    int updateByPrimaryKeySelective(VersionControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated Sat Jan 20 10:15:32 CST 2018
     */
    @Update({
        "update version_control",
        "set version = #{version,jdbcType=VARCHAR},",
          "platform = #{platform,jdbcType=INTEGER},",
          "update_description = #{updateDescription,jdbcType=VARCHAR},",
          "update_url = #{updateUrl,jdbcType=VARCHAR},",
          "force_update = #{forceUpdate,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(VersionControl record);
}