package com.m2m.mapper;

import com.m2m.domain.VoteOption;
import com.m2m.domain.VoteOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface VoteOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    int countByExample(VoteOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    int deleteByExample(VoteOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    @Delete({
        "delete from vote_option",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    @Insert({
        "insert into vote_option (id, voteId, ",
        "optionName, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{voteid,jdbcType=BIGINT}, ",
        "#{optionname,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(VoteOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    int insertSelective(VoteOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    List<VoteOption> selectByExample(VoteOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    @Select({
        "select",
        "id, voteId, optionName, create_time",
        "from vote_option",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    VoteOption selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") VoteOption record, @Param("example") VoteOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    int updateByExample(@Param("record") VoteOption record, @Param("example") VoteOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    int updateByPrimaryKeySelective(VoteOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    @Update({
        "update vote_option",
        "set voteId = #{voteid,jdbcType=BIGINT},",
          "optionName = #{optionname,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(VoteOption record);
}