package com.m2m.mapper;

import com.m2m.domain.VoteInfo;
import com.m2m.domain.VoteInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface VoteInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_info
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    int countByExample(VoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_info
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    int deleteByExample(VoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_info
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    @Delete({
        "delete from vote_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_info
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    @Insert({
        "insert into vote_info (id, uid, topicId, ",
        "title, type, status, ",
        "create_time)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT}, #{topicid,jdbcType=BIGINT}, ",
        "#{title,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, #{status,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(VoteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_info
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    int insertSelective(VoteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_info
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    List<VoteInfo> selectByExample(VoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_info
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    @Select({
        "select",
        "id, uid, topicId, title, type, status, create_time",
        "from vote_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    VoteInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_info
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") VoteInfo record, @Param("example") VoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_info
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    int updateByExample(@Param("record") VoteInfo record, @Param("example") VoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_info
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    int updateByPrimaryKeySelective(VoteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_info
     *
     * @mbggenerated Wed Jan 17 14:32:35 CST 2018
     */
    @Update({
        "update vote_info",
        "set uid = #{uid,jdbcType=BIGINT},",
          "topicId = #{topicid,jdbcType=BIGINT},",
          "title = #{title,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(VoteInfo record);
}