package com.m2m.domain;

public class AndroidCrash {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_crash.id
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_crash.app_version
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    private String appVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_crash.app_build_version
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    private String appBuildVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_crash.device_os
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    private String deviceOs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_crash.device_type
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    private String deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_crash.channel
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_crash.platform
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_crash.created_at
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    private Long createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_crash.crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    private String crash;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_crash.id
     *
     * @return the value of android_crash.id
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_crash.id
     *
     * @param id the value for android_crash.id
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_crash.app_version
     *
     * @return the value of android_crash.app_version
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_crash.app_version
     *
     * @param appVersion the value for android_crash.app_version
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_crash.app_build_version
     *
     * @return the value of android_crash.app_build_version
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public String getAppBuildVersion() {
        return appBuildVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_crash.app_build_version
     *
     * @param appBuildVersion the value for android_crash.app_build_version
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public void setAppBuildVersion(String appBuildVersion) {
        this.appBuildVersion = appBuildVersion == null ? null : appBuildVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_crash.device_os
     *
     * @return the value of android_crash.device_os
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public String getDeviceOs() {
        return deviceOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_crash.device_os
     *
     * @param deviceOs the value for android_crash.device_os
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public void setDeviceOs(String deviceOs) {
        this.deviceOs = deviceOs == null ? null : deviceOs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_crash.device_type
     *
     * @return the value of android_crash.device_type
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_crash.device_type
     *
     * @param deviceType the value for android_crash.device_type
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_crash.channel
     *
     * @return the value of android_crash.channel
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_crash.channel
     *
     * @param channel the value for android_crash.channel
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_crash.platform
     *
     * @return the value of android_crash.platform
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_crash.platform
     *
     * @param platform the value for android_crash.platform
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_crash.created_at
     *
     * @return the value of android_crash.created_at
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_crash.created_at
     *
     * @param createdAt the value for android_crash.created_at
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_crash.crash
     *
     * @return the value of android_crash.crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public String getCrash() {
        return crash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_crash.crash
     *
     * @param crash the value for android_crash.crash
     *
     * @mbggenerated Mon Jan 15 09:57:55 CST 2018
     */
    public void setCrash(String crash) {
        this.crash = crash == null ? null : crash.trim();
    }
}