package com.m2m.domain;

public class BlockTopic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_topic.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_topic.topic_id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_topic.uid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_topic.id
     *
     * @return the value of block_topic.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_topic.id
     *
     * @param id the value for block_topic.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_topic.topic_id
     *
     * @return the value of block_topic.topic_id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_topic.topic_id
     *
     * @param topicId the value for block_topic.topic_id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_topic.uid
     *
     * @return the value of block_topic.uid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_topic.uid
     *
     * @param uid the value for block_topic.uid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }
}