package com.m2m.domain;

import java.util.Date;

public class ContentTagsDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_tags_details.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_tags_details.cid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_tags_details.tid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_tags_details.uid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_tags_details.create_time
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_tags_details.id
     *
     * @return the value of content_tags_details.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_tags_details.id
     *
     * @param id the value for content_tags_details.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_tags_details.cid
     *
     * @return the value of content_tags_details.cid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_tags_details.cid
     *
     * @param cid the value for content_tags_details.cid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_tags_details.tid
     *
     * @return the value of content_tags_details.tid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_tags_details.tid
     *
     * @param tid the value for content_tags_details.tid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_tags_details.uid
     *
     * @return the value of content_tags_details.uid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_tags_details.uid
     *
     * @param uid the value for content_tags_details.uid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_tags_details.create_time
     *
     * @return the value of content_tags_details.create_time
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_tags_details.create_time
     *
     * @param createTime the value for content_tags_details.create_time
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}