package com.m2m.domain;

public class ContentImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_image.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_image.cover
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Integer cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_image.cid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_image.image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_image.id
     *
     * @return the value of content_image.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_image.id
     *
     * @param id the value for content_image.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_image.cover
     *
     * @return the value of content_image.cover
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Integer getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_image.cover
     *
     * @param cover the value for content_image.cover
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setCover(Integer cover) {
        this.cover = cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_image.cid
     *
     * @return the value of content_image.cid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_image.cid
     *
     * @param cid the value for content_image.cid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_image.image
     *
     * @return the value of content_image.image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_image.image
     *
     * @param image the value for content_image.image
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
}