package com.m2m.domain;

import java.util.Date;

public class LotteryContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_content.id
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_content.lottery_id
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    private Long lotteryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_content.uid
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_content.content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_content.create_time
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_content.id
     *
     * @return the value of lottery_content.id
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_content.id
     *
     * @param id the value for lottery_content.id
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_content.lottery_id
     *
     * @return the value of lottery_content.lottery_id
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    public Long getLotteryId() {
        return lotteryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_content.lottery_id
     *
     * @param lotteryId the value for lottery_content.lottery_id
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    public void setLotteryId(Long lotteryId) {
        this.lotteryId = lotteryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_content.uid
     *
     * @return the value of lottery_content.uid
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_content.uid
     *
     * @param uid the value for lottery_content.uid
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_content.content
     *
     * @return the value of lottery_content.content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_content.content
     *
     * @param content the value for lottery_content.content
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_content.create_time
     *
     * @return the value of lottery_content.create_time
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_content.create_time
     *
     * @param createTime the value for lottery_content.create_time
     *
     * @mbggenerated Mon Jan 22 14:22:51 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}