package com.m2m.domain;

public class SystemConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.default_follow
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private String defaultFollow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.read_count_start
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Integer readCountStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.read_count_end
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Integer readCountEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.default_subscribe
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private String defaultSubscribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.id
     *
     * @return the value of system_config.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.id
     *
     * @param id the value for system_config.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.default_follow
     *
     * @return the value of system_config.default_follow
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public String getDefaultFollow() {
        return defaultFollow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.default_follow
     *
     * @param defaultFollow the value for system_config.default_follow
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setDefaultFollow(String defaultFollow) {
        this.defaultFollow = defaultFollow == null ? null : defaultFollow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.read_count_start
     *
     * @return the value of system_config.read_count_start
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Integer getReadCountStart() {
        return readCountStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.read_count_start
     *
     * @param readCountStart the value for system_config.read_count_start
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setReadCountStart(Integer readCountStart) {
        this.readCountStart = readCountStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.read_count_end
     *
     * @return the value of system_config.read_count_end
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Integer getReadCountEnd() {
        return readCountEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.read_count_end
     *
     * @param readCountEnd the value for system_config.read_count_end
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setReadCountEnd(Integer readCountEnd) {
        this.readCountEnd = readCountEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.default_subscribe
     *
     * @return the value of system_config.default_subscribe
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public String getDefaultSubscribe() {
        return defaultSubscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.default_subscribe
     *
     * @param defaultSubscribe the value for system_config.default_subscribe
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setDefaultSubscribe(String defaultSubscribe) {
        this.defaultSubscribe = defaultSubscribe == null ? null : defaultSubscribe.trim();
    }
}