package com.m2m.domain;

import java.util.ArrayList;
import java.util.List;

public class SystemConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public SystemConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowIsNull() {
            addCriterion("default_follow is null");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowIsNotNull() {
            addCriterion("default_follow is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowEqualTo(String value) {
            addCriterion("default_follow =", value, "defaultFollow");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowNotEqualTo(String value) {
            addCriterion("default_follow <>", value, "defaultFollow");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowGreaterThan(String value) {
            addCriterion("default_follow >", value, "defaultFollow");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowGreaterThanOrEqualTo(String value) {
            addCriterion("default_follow >=", value, "defaultFollow");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowLessThan(String value) {
            addCriterion("default_follow <", value, "defaultFollow");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowLessThanOrEqualTo(String value) {
            addCriterion("default_follow <=", value, "defaultFollow");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowLike(String value) {
            addCriterion("default_follow like", value, "defaultFollow");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowNotLike(String value) {
            addCriterion("default_follow not like", value, "defaultFollow");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowIn(List<String> values) {
            addCriterion("default_follow in", values, "defaultFollow");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowNotIn(List<String> values) {
            addCriterion("default_follow not in", values, "defaultFollow");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowBetween(String value1, String value2) {
            addCriterion("default_follow between", value1, value2, "defaultFollow");
            return (Criteria) this;
        }

        public Criteria andDefaultFollowNotBetween(String value1, String value2) {
            addCriterion("default_follow not between", value1, value2, "defaultFollow");
            return (Criteria) this;
        }

        public Criteria andReadCountStartIsNull() {
            addCriterion("read_count_start is null");
            return (Criteria) this;
        }

        public Criteria andReadCountStartIsNotNull() {
            addCriterion("read_count_start is not null");
            return (Criteria) this;
        }

        public Criteria andReadCountStartEqualTo(Integer value) {
            addCriterion("read_count_start =", value, "readCountStart");
            return (Criteria) this;
        }

        public Criteria andReadCountStartNotEqualTo(Integer value) {
            addCriterion("read_count_start <>", value, "readCountStart");
            return (Criteria) this;
        }

        public Criteria andReadCountStartGreaterThan(Integer value) {
            addCriterion("read_count_start >", value, "readCountStart");
            return (Criteria) this;
        }

        public Criteria andReadCountStartGreaterThanOrEqualTo(Integer value) {
            addCriterion("read_count_start >=", value, "readCountStart");
            return (Criteria) this;
        }

        public Criteria andReadCountStartLessThan(Integer value) {
            addCriterion("read_count_start <", value, "readCountStart");
            return (Criteria) this;
        }

        public Criteria andReadCountStartLessThanOrEqualTo(Integer value) {
            addCriterion("read_count_start <=", value, "readCountStart");
            return (Criteria) this;
        }

        public Criteria andReadCountStartIn(List<Integer> values) {
            addCriterion("read_count_start in", values, "readCountStart");
            return (Criteria) this;
        }

        public Criteria andReadCountStartNotIn(List<Integer> values) {
            addCriterion("read_count_start not in", values, "readCountStart");
            return (Criteria) this;
        }

        public Criteria andReadCountStartBetween(Integer value1, Integer value2) {
            addCriterion("read_count_start between", value1, value2, "readCountStart");
            return (Criteria) this;
        }

        public Criteria andReadCountStartNotBetween(Integer value1, Integer value2) {
            addCriterion("read_count_start not between", value1, value2, "readCountStart");
            return (Criteria) this;
        }

        public Criteria andReadCountEndIsNull() {
            addCriterion("read_count_end is null");
            return (Criteria) this;
        }

        public Criteria andReadCountEndIsNotNull() {
            addCriterion("read_count_end is not null");
            return (Criteria) this;
        }

        public Criteria andReadCountEndEqualTo(Integer value) {
            addCriterion("read_count_end =", value, "readCountEnd");
            return (Criteria) this;
        }

        public Criteria andReadCountEndNotEqualTo(Integer value) {
            addCriterion("read_count_end <>", value, "readCountEnd");
            return (Criteria) this;
        }

        public Criteria andReadCountEndGreaterThan(Integer value) {
            addCriterion("read_count_end >", value, "readCountEnd");
            return (Criteria) this;
        }

        public Criteria andReadCountEndGreaterThanOrEqualTo(Integer value) {
            addCriterion("read_count_end >=", value, "readCountEnd");
            return (Criteria) this;
        }

        public Criteria andReadCountEndLessThan(Integer value) {
            addCriterion("read_count_end <", value, "readCountEnd");
            return (Criteria) this;
        }

        public Criteria andReadCountEndLessThanOrEqualTo(Integer value) {
            addCriterion("read_count_end <=", value, "readCountEnd");
            return (Criteria) this;
        }

        public Criteria andReadCountEndIn(List<Integer> values) {
            addCriterion("read_count_end in", values, "readCountEnd");
            return (Criteria) this;
        }

        public Criteria andReadCountEndNotIn(List<Integer> values) {
            addCriterion("read_count_end not in", values, "readCountEnd");
            return (Criteria) this;
        }

        public Criteria andReadCountEndBetween(Integer value1, Integer value2) {
            addCriterion("read_count_end between", value1, value2, "readCountEnd");
            return (Criteria) this;
        }

        public Criteria andReadCountEndNotBetween(Integer value1, Integer value2) {
            addCriterion("read_count_end not between", value1, value2, "readCountEnd");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeIsNull() {
            addCriterion("default_subscribe is null");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeIsNotNull() {
            addCriterion("default_subscribe is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeEqualTo(String value) {
            addCriterion("default_subscribe =", value, "defaultSubscribe");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeNotEqualTo(String value) {
            addCriterion("default_subscribe <>", value, "defaultSubscribe");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeGreaterThan(String value) {
            addCriterion("default_subscribe >", value, "defaultSubscribe");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeGreaterThanOrEqualTo(String value) {
            addCriterion("default_subscribe >=", value, "defaultSubscribe");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeLessThan(String value) {
            addCriterion("default_subscribe <", value, "defaultSubscribe");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeLessThanOrEqualTo(String value) {
            addCriterion("default_subscribe <=", value, "defaultSubscribe");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeLike(String value) {
            addCriterion("default_subscribe like", value, "defaultSubscribe");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeNotLike(String value) {
            addCriterion("default_subscribe not like", value, "defaultSubscribe");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeIn(List<String> values) {
            addCriterion("default_subscribe in", values, "defaultSubscribe");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeNotIn(List<String> values) {
            addCriterion("default_subscribe not in", values, "defaultSubscribe");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeBetween(String value1, String value2) {
            addCriterion("default_subscribe between", value1, value2, "defaultSubscribe");
            return (Criteria) this;
        }

        public Criteria andDefaultSubscribeNotBetween(String value1, String value2) {
            addCriterion("default_subscribe not between", value1, value2, "defaultSubscribe");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_config
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 11 17:51:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_config
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}