package com.m2m.domain;

public class TagTrainSampleWithBLOBs extends TagTrainSample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_train_sample.summary
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_train_sample.keywords
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private String keywords;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_train_sample.summary
     *
     * @return the value of tag_train_sample.summary
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_train_sample.summary
     *
     * @param summary the value for tag_train_sample.summary
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_train_sample.keywords
     *
     * @return the value of tag_train_sample.keywords
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_train_sample.keywords
     *
     * @param keywords the value for tag_train_sample.keywords
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }
}