package com.m2m.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TopicDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    public TopicDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTopicIdIsNull() {
            addCriterion("topic_id is null");
            return (Criteria) this;
        }

        public Criteria andTopicIdIsNotNull() {
            addCriterion("topic_id is not null");
            return (Criteria) this;
        }

        public Criteria andTopicIdEqualTo(Long value) {
            addCriterion("topic_id =", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdNotEqualTo(Long value) {
            addCriterion("topic_id <>", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdGreaterThan(Long value) {
            addCriterion("topic_id >", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdGreaterThanOrEqualTo(Long value) {
            addCriterion("topic_id >=", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdLessThan(Long value) {
            addCriterion("topic_id <", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdLessThanOrEqualTo(Long value) {
            addCriterion("topic_id <=", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdIn(List<Long> values) {
            addCriterion("topic_id in", values, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdNotIn(List<Long> values) {
            addCriterion("topic_id not in", values, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdBetween(Long value1, Long value2) {
            addCriterion("topic_id between", value1, value2, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdNotBetween(Long value1, Long value2) {
            addCriterion("topic_id not between", value1, value2, "topicId");
            return (Criteria) this;
        }

        public Criteria andLastPriceIsNull() {
            addCriterion("last_price is null");
            return (Criteria) this;
        }

        public Criteria andLastPriceIsNotNull() {
            addCriterion("last_price is not null");
            return (Criteria) this;
        }

        public Criteria andLastPriceEqualTo(Integer value) {
            addCriterion("last_price =", value, "lastPrice");
            return (Criteria) this;
        }

        public Criteria andLastPriceNotEqualTo(Integer value) {
            addCriterion("last_price <>", value, "lastPrice");
            return (Criteria) this;
        }

        public Criteria andLastPriceGreaterThan(Integer value) {
            addCriterion("last_price >", value, "lastPrice");
            return (Criteria) this;
        }

        public Criteria andLastPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("last_price >=", value, "lastPrice");
            return (Criteria) this;
        }

        public Criteria andLastPriceLessThan(Integer value) {
            addCriterion("last_price <", value, "lastPrice");
            return (Criteria) this;
        }

        public Criteria andLastPriceLessThanOrEqualTo(Integer value) {
            addCriterion("last_price <=", value, "lastPrice");
            return (Criteria) this;
        }

        public Criteria andLastPriceIn(List<Integer> values) {
            addCriterion("last_price in", values, "lastPrice");
            return (Criteria) this;
        }

        public Criteria andLastPriceNotIn(List<Integer> values) {
            addCriterion("last_price not in", values, "lastPrice");
            return (Criteria) this;
        }

        public Criteria andLastPriceBetween(Integer value1, Integer value2) {
            addCriterion("last_price between", value1, value2, "lastPrice");
            return (Criteria) this;
        }

        public Criteria andLastPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("last_price not between", value1, value2, "lastPrice");
            return (Criteria) this;
        }

        public Criteria andLastPriceIncrIsNull() {
            addCriterion("last_price_incr is null");
            return (Criteria) this;
        }

        public Criteria andLastPriceIncrIsNotNull() {
            addCriterion("last_price_incr is not null");
            return (Criteria) this;
        }

        public Criteria andLastPriceIncrEqualTo(Integer value) {
            addCriterion("last_price_incr =", value, "lastPriceIncr");
            return (Criteria) this;
        }

        public Criteria andLastPriceIncrNotEqualTo(Integer value) {
            addCriterion("last_price_incr <>", value, "lastPriceIncr");
            return (Criteria) this;
        }

        public Criteria andLastPriceIncrGreaterThan(Integer value) {
            addCriterion("last_price_incr >", value, "lastPriceIncr");
            return (Criteria) this;
        }

        public Criteria andLastPriceIncrGreaterThanOrEqualTo(Integer value) {
            addCriterion("last_price_incr >=", value, "lastPriceIncr");
            return (Criteria) this;
        }

        public Criteria andLastPriceIncrLessThan(Integer value) {
            addCriterion("last_price_incr <", value, "lastPriceIncr");
            return (Criteria) this;
        }

        public Criteria andLastPriceIncrLessThanOrEqualTo(Integer value) {
            addCriterion("last_price_incr <=", value, "lastPriceIncr");
            return (Criteria) this;
        }

        public Criteria andLastPriceIncrIn(List<Integer> values) {
            addCriterion("last_price_incr in", values, "lastPriceIncr");
            return (Criteria) this;
        }

        public Criteria andLastPriceIncrNotIn(List<Integer> values) {
            addCriterion("last_price_incr not in", values, "lastPriceIncr");
            return (Criteria) this;
        }

        public Criteria andLastPriceIncrBetween(Integer value1, Integer value2) {
            addCriterion("last_price_incr between", value1, value2, "lastPriceIncr");
            return (Criteria) this;
        }

        public Criteria andLastPriceIncrNotBetween(Integer value1, Integer value2) {
            addCriterion("last_price_incr not between", value1, value2, "lastPriceIncr");
            return (Criteria) this;
        }

        public Criteria andStealPriceIsNull() {
            addCriterion("steal_price is null");
            return (Criteria) this;
        }

        public Criteria andStealPriceIsNotNull() {
            addCriterion("steal_price is not null");
            return (Criteria) this;
        }

        public Criteria andStealPriceEqualTo(Integer value) {
            addCriterion("steal_price =", value, "stealPrice");
            return (Criteria) this;
        }

        public Criteria andStealPriceNotEqualTo(Integer value) {
            addCriterion("steal_price <>", value, "stealPrice");
            return (Criteria) this;
        }

        public Criteria andStealPriceGreaterThan(Integer value) {
            addCriterion("steal_price >", value, "stealPrice");
            return (Criteria) this;
        }

        public Criteria andStealPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("steal_price >=", value, "stealPrice");
            return (Criteria) this;
        }

        public Criteria andStealPriceLessThan(Integer value) {
            addCriterion("steal_price <", value, "stealPrice");
            return (Criteria) this;
        }

        public Criteria andStealPriceLessThanOrEqualTo(Integer value) {
            addCriterion("steal_price <=", value, "stealPrice");
            return (Criteria) this;
        }

        public Criteria andStealPriceIn(List<Integer> values) {
            addCriterion("steal_price in", values, "stealPrice");
            return (Criteria) this;
        }

        public Criteria andStealPriceNotIn(List<Integer> values) {
            addCriterion("steal_price not in", values, "stealPrice");
            return (Criteria) this;
        }

        public Criteria andStealPriceBetween(Integer value1, Integer value2) {
            addCriterion("steal_price between", value1, value2, "stealPrice");
            return (Criteria) this;
        }

        public Criteria andStealPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("steal_price not between", value1, value2, "stealPrice");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDiligentlyIsNull() {
            addCriterion("diligently is null");
            return (Criteria) this;
        }

        public Criteria andDiligentlyIsNotNull() {
            addCriterion("diligently is not null");
            return (Criteria) this;
        }

        public Criteria andDiligentlyEqualTo(Double value) {
            addCriterion("diligently =", value, "diligently");
            return (Criteria) this;
        }

        public Criteria andDiligentlyNotEqualTo(Double value) {
            addCriterion("diligently <>", value, "diligently");
            return (Criteria) this;
        }

        public Criteria andDiligentlyGreaterThan(Double value) {
            addCriterion("diligently >", value, "diligently");
            return (Criteria) this;
        }

        public Criteria andDiligentlyGreaterThanOrEqualTo(Double value) {
            addCriterion("diligently >=", value, "diligently");
            return (Criteria) this;
        }

        public Criteria andDiligentlyLessThan(Double value) {
            addCriterion("diligently <", value, "diligently");
            return (Criteria) this;
        }

        public Criteria andDiligentlyLessThanOrEqualTo(Double value) {
            addCriterion("diligently <=", value, "diligently");
            return (Criteria) this;
        }

        public Criteria andDiligentlyIn(List<Double> values) {
            addCriterion("diligently in", values, "diligently");
            return (Criteria) this;
        }

        public Criteria andDiligentlyNotIn(List<Double> values) {
            addCriterion("diligently not in", values, "diligently");
            return (Criteria) this;
        }

        public Criteria andDiligentlyBetween(Double value1, Double value2) {
            addCriterion("diligently between", value1, value2, "diligently");
            return (Criteria) this;
        }

        public Criteria andDiligentlyNotBetween(Double value1, Double value2) {
            addCriterion("diligently not between", value1, value2, "diligently");
            return (Criteria) this;
        }

        public Criteria andApproveIsNull() {
            addCriterion("approve is null");
            return (Criteria) this;
        }

        public Criteria andApproveIsNotNull() {
            addCriterion("approve is not null");
            return (Criteria) this;
        }

        public Criteria andApproveEqualTo(Double value) {
            addCriterion("approve =", value, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveNotEqualTo(Double value) {
            addCriterion("approve <>", value, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveGreaterThan(Double value) {
            addCriterion("approve >", value, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveGreaterThanOrEqualTo(Double value) {
            addCriterion("approve >=", value, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveLessThan(Double value) {
            addCriterion("approve <", value, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveLessThanOrEqualTo(Double value) {
            addCriterion("approve <=", value, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveIn(List<Double> values) {
            addCriterion("approve in", values, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveNotIn(List<Double> values) {
            addCriterion("approve not in", values, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveBetween(Double value1, Double value2) {
            addCriterion("approve between", value1, value2, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveNotBetween(Double value1, Double value2) {
            addCriterion("approve not between", value1, value2, "approve");
            return (Criteria) this;
        }

        public Criteria andUpdateTextLengthIsNull() {
            addCriterion("update_text_length is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTextLengthIsNotNull() {
            addCriterion("update_text_length is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTextLengthEqualTo(Integer value) {
            addCriterion("update_text_length =", value, "updateTextLength");
            return (Criteria) this;
        }

        public Criteria andUpdateTextLengthNotEqualTo(Integer value) {
            addCriterion("update_text_length <>", value, "updateTextLength");
            return (Criteria) this;
        }

        public Criteria andUpdateTextLengthGreaterThan(Integer value) {
            addCriterion("update_text_length >", value, "updateTextLength");
            return (Criteria) this;
        }

        public Criteria andUpdateTextLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_text_length >=", value, "updateTextLength");
            return (Criteria) this;
        }

        public Criteria andUpdateTextLengthLessThan(Integer value) {
            addCriterion("update_text_length <", value, "updateTextLength");
            return (Criteria) this;
        }

        public Criteria andUpdateTextLengthLessThanOrEqualTo(Integer value) {
            addCriterion("update_text_length <=", value, "updateTextLength");
            return (Criteria) this;
        }

        public Criteria andUpdateTextLengthIn(List<Integer> values) {
            addCriterion("update_text_length in", values, "updateTextLength");
            return (Criteria) this;
        }

        public Criteria andUpdateTextLengthNotIn(List<Integer> values) {
            addCriterion("update_text_length not in", values, "updateTextLength");
            return (Criteria) this;
        }

        public Criteria andUpdateTextLengthBetween(Integer value1, Integer value2) {
            addCriterion("update_text_length between", value1, value2, "updateTextLength");
            return (Criteria) this;
        }

        public Criteria andUpdateTextLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("update_text_length not between", value1, value2, "updateTextLength");
            return (Criteria) this;
        }

        public Criteria andUpdateTextCountIsNull() {
            addCriterion("update_text_count is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTextCountIsNotNull() {
            addCriterion("update_text_count is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTextCountEqualTo(Integer value) {
            addCriterion("update_text_count =", value, "updateTextCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTextCountNotEqualTo(Integer value) {
            addCriterion("update_text_count <>", value, "updateTextCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTextCountGreaterThan(Integer value) {
            addCriterion("update_text_count >", value, "updateTextCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTextCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_text_count >=", value, "updateTextCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTextCountLessThan(Integer value) {
            addCriterion("update_text_count <", value, "updateTextCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTextCountLessThanOrEqualTo(Integer value) {
            addCriterion("update_text_count <=", value, "updateTextCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTextCountIn(List<Integer> values) {
            addCriterion("update_text_count in", values, "updateTextCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTextCountNotIn(List<Integer> values) {
            addCriterion("update_text_count not in", values, "updateTextCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTextCountBetween(Integer value1, Integer value2) {
            addCriterion("update_text_count between", value1, value2, "updateTextCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTextCountNotBetween(Integer value1, Integer value2) {
            addCriterion("update_text_count not between", value1, value2, "updateTextCount");
            return (Criteria) this;
        }

        public Criteria andUpdateImageCountIsNull() {
            addCriterion("update_image_count is null");
            return (Criteria) this;
        }

        public Criteria andUpdateImageCountIsNotNull() {
            addCriterion("update_image_count is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateImageCountEqualTo(Integer value) {
            addCriterion("update_image_count =", value, "updateImageCount");
            return (Criteria) this;
        }

        public Criteria andUpdateImageCountNotEqualTo(Integer value) {
            addCriterion("update_image_count <>", value, "updateImageCount");
            return (Criteria) this;
        }

        public Criteria andUpdateImageCountGreaterThan(Integer value) {
            addCriterion("update_image_count >", value, "updateImageCount");
            return (Criteria) this;
        }

        public Criteria andUpdateImageCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_image_count >=", value, "updateImageCount");
            return (Criteria) this;
        }

        public Criteria andUpdateImageCountLessThan(Integer value) {
            addCriterion("update_image_count <", value, "updateImageCount");
            return (Criteria) this;
        }

        public Criteria andUpdateImageCountLessThanOrEqualTo(Integer value) {
            addCriterion("update_image_count <=", value, "updateImageCount");
            return (Criteria) this;
        }

        public Criteria andUpdateImageCountIn(List<Integer> values) {
            addCriterion("update_image_count in", values, "updateImageCount");
            return (Criteria) this;
        }

        public Criteria andUpdateImageCountNotIn(List<Integer> values) {
            addCriterion("update_image_count not in", values, "updateImageCount");
            return (Criteria) this;
        }

        public Criteria andUpdateImageCountBetween(Integer value1, Integer value2) {
            addCriterion("update_image_count between", value1, value2, "updateImageCount");
            return (Criteria) this;
        }

        public Criteria andUpdateImageCountNotBetween(Integer value1, Integer value2) {
            addCriterion("update_image_count not between", value1, value2, "updateImageCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioCountIsNull() {
            addCriterion("update_vedio_count is null");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioCountIsNotNull() {
            addCriterion("update_vedio_count is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioCountEqualTo(Integer value) {
            addCriterion("update_vedio_count =", value, "updateVedioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioCountNotEqualTo(Integer value) {
            addCriterion("update_vedio_count <>", value, "updateVedioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioCountGreaterThan(Integer value) {
            addCriterion("update_vedio_count >", value, "updateVedioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_vedio_count >=", value, "updateVedioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioCountLessThan(Integer value) {
            addCriterion("update_vedio_count <", value, "updateVedioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioCountLessThanOrEqualTo(Integer value) {
            addCriterion("update_vedio_count <=", value, "updateVedioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioCountIn(List<Integer> values) {
            addCriterion("update_vedio_count in", values, "updateVedioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioCountNotIn(List<Integer> values) {
            addCriterion("update_vedio_count not in", values, "updateVedioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioCountBetween(Integer value1, Integer value2) {
            addCriterion("update_vedio_count between", value1, value2, "updateVedioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioCountNotBetween(Integer value1, Integer value2) {
            addCriterion("update_vedio_count not between", value1, value2, "updateVedioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioLengthIsNull() {
            addCriterion("update_vedio_length is null");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioLengthIsNotNull() {
            addCriterion("update_vedio_length is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioLengthEqualTo(Integer value) {
            addCriterion("update_vedio_length =", value, "updateVedioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioLengthNotEqualTo(Integer value) {
            addCriterion("update_vedio_length <>", value, "updateVedioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioLengthGreaterThan(Integer value) {
            addCriterion("update_vedio_length >", value, "updateVedioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_vedio_length >=", value, "updateVedioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioLengthLessThan(Integer value) {
            addCriterion("update_vedio_length <", value, "updateVedioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioLengthLessThanOrEqualTo(Integer value) {
            addCriterion("update_vedio_length <=", value, "updateVedioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioLengthIn(List<Integer> values) {
            addCriterion("update_vedio_length in", values, "updateVedioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioLengthNotIn(List<Integer> values) {
            addCriterion("update_vedio_length not in", values, "updateVedioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioLengthBetween(Integer value1, Integer value2) {
            addCriterion("update_vedio_length between", value1, value2, "updateVedioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateVedioLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("update_vedio_length not between", value1, value2, "updateVedioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioCountIsNull() {
            addCriterion("update_audio_count is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioCountIsNotNull() {
            addCriterion("update_audio_count is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioCountEqualTo(Integer value) {
            addCriterion("update_audio_count =", value, "updateAudioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioCountNotEqualTo(Integer value) {
            addCriterion("update_audio_count <>", value, "updateAudioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioCountGreaterThan(Integer value) {
            addCriterion("update_audio_count >", value, "updateAudioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_audio_count >=", value, "updateAudioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioCountLessThan(Integer value) {
            addCriterion("update_audio_count <", value, "updateAudioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioCountLessThanOrEqualTo(Integer value) {
            addCriterion("update_audio_count <=", value, "updateAudioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioCountIn(List<Integer> values) {
            addCriterion("update_audio_count in", values, "updateAudioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioCountNotIn(List<Integer> values) {
            addCriterion("update_audio_count not in", values, "updateAudioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioCountBetween(Integer value1, Integer value2) {
            addCriterion("update_audio_count between", value1, value2, "updateAudioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioCountNotBetween(Integer value1, Integer value2) {
            addCriterion("update_audio_count not between", value1, value2, "updateAudioCount");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioLengthIsNull() {
            addCriterion("update_audio_length is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioLengthIsNotNull() {
            addCriterion("update_audio_length is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioLengthEqualTo(Integer value) {
            addCriterion("update_audio_length =", value, "updateAudioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioLengthNotEqualTo(Integer value) {
            addCriterion("update_audio_length <>", value, "updateAudioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioLengthGreaterThan(Integer value) {
            addCriterion("update_audio_length >", value, "updateAudioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_audio_length >=", value, "updateAudioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioLengthLessThan(Integer value) {
            addCriterion("update_audio_length <", value, "updateAudioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioLengthLessThanOrEqualTo(Integer value) {
            addCriterion("update_audio_length <=", value, "updateAudioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioLengthIn(List<Integer> values) {
            addCriterion("update_audio_length in", values, "updateAudioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioLengthNotIn(List<Integer> values) {
            addCriterion("update_audio_length not in", values, "updateAudioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioLengthBetween(Integer value1, Integer value2) {
            addCriterion("update_audio_length between", value1, value2, "updateAudioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateAudioLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("update_audio_length not between", value1, value2, "updateAudioLength");
            return (Criteria) this;
        }

        public Criteria andUpdateVoteCountIsNull() {
            addCriterion("update_vote_count is null");
            return (Criteria) this;
        }

        public Criteria andUpdateVoteCountIsNotNull() {
            addCriterion("update_vote_count is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateVoteCountEqualTo(Integer value) {
            addCriterion("update_vote_count =", value, "updateVoteCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVoteCountNotEqualTo(Integer value) {
            addCriterion("update_vote_count <>", value, "updateVoteCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVoteCountGreaterThan(Integer value) {
            addCriterion("update_vote_count >", value, "updateVoteCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVoteCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_vote_count >=", value, "updateVoteCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVoteCountLessThan(Integer value) {
            addCriterion("update_vote_count <", value, "updateVoteCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVoteCountLessThanOrEqualTo(Integer value) {
            addCriterion("update_vote_count <=", value, "updateVoteCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVoteCountIn(List<Integer> values) {
            addCriterion("update_vote_count in", values, "updateVoteCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVoteCountNotIn(List<Integer> values) {
            addCriterion("update_vote_count not in", values, "updateVoteCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVoteCountBetween(Integer value1, Integer value2) {
            addCriterion("update_vote_count between", value1, value2, "updateVoteCount");
            return (Criteria) this;
        }

        public Criteria andUpdateVoteCountNotBetween(Integer value1, Integer value2) {
            addCriterion("update_vote_count not between", value1, value2, "updateVoteCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTeaseCountIsNull() {
            addCriterion("update_tease_count is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTeaseCountIsNotNull() {
            addCriterion("update_tease_count is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTeaseCountEqualTo(Integer value) {
            addCriterion("update_tease_count =", value, "updateTeaseCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTeaseCountNotEqualTo(Integer value) {
            addCriterion("update_tease_count <>", value, "updateTeaseCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTeaseCountGreaterThan(Integer value) {
            addCriterion("update_tease_count >", value, "updateTeaseCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTeaseCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_tease_count >=", value, "updateTeaseCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTeaseCountLessThan(Integer value) {
            addCriterion("update_tease_count <", value, "updateTeaseCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTeaseCountLessThanOrEqualTo(Integer value) {
            addCriterion("update_tease_count <=", value, "updateTeaseCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTeaseCountIn(List<Integer> values) {
            addCriterion("update_tease_count in", values, "updateTeaseCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTeaseCountNotIn(List<Integer> values) {
            addCriterion("update_tease_count not in", values, "updateTeaseCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTeaseCountBetween(Integer value1, Integer value2) {
            addCriterion("update_tease_count between", value1, value2, "updateTeaseCount");
            return (Criteria) this;
        }

        public Criteria andUpdateTeaseCountNotBetween(Integer value1, Integer value2) {
            addCriterion("update_tease_count not between", value1, value2, "updateTeaseCount");
            return (Criteria) this;
        }

        public Criteria andUpdateDayCountIsNull() {
            addCriterion("update_day_count is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDayCountIsNotNull() {
            addCriterion("update_day_count is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDayCountEqualTo(Integer value) {
            addCriterion("update_day_count =", value, "updateDayCount");
            return (Criteria) this;
        }

        public Criteria andUpdateDayCountNotEqualTo(Integer value) {
            addCriterion("update_day_count <>", value, "updateDayCount");
            return (Criteria) this;
        }

        public Criteria andUpdateDayCountGreaterThan(Integer value) {
            addCriterion("update_day_count >", value, "updateDayCount");
            return (Criteria) this;
        }

        public Criteria andUpdateDayCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_day_count >=", value, "updateDayCount");
            return (Criteria) this;
        }

        public Criteria andUpdateDayCountLessThan(Integer value) {
            addCriterion("update_day_count <", value, "updateDayCount");
            return (Criteria) this;
        }

        public Criteria andUpdateDayCountLessThanOrEqualTo(Integer value) {
            addCriterion("update_day_count <=", value, "updateDayCount");
            return (Criteria) this;
        }

        public Criteria andUpdateDayCountIn(List<Integer> values) {
            addCriterion("update_day_count in", values, "updateDayCount");
            return (Criteria) this;
        }

        public Criteria andUpdateDayCountNotIn(List<Integer> values) {
            addCriterion("update_day_count not in", values, "updateDayCount");
            return (Criteria) this;
        }

        public Criteria andUpdateDayCountBetween(Integer value1, Integer value2) {
            addCriterion("update_day_count between", value1, value2, "updateDayCount");
            return (Criteria) this;
        }

        public Criteria andUpdateDayCountNotBetween(Integer value1, Integer value2) {
            addCriterion("update_day_count not between", value1, value2, "updateDayCount");
            return (Criteria) this;
        }

        public Criteria andReviewTextCountIsNull() {
            addCriterion("review_text_count is null");
            return (Criteria) this;
        }

        public Criteria andReviewTextCountIsNotNull() {
            addCriterion("review_text_count is not null");
            return (Criteria) this;
        }

        public Criteria andReviewTextCountEqualTo(Integer value) {
            addCriterion("review_text_count =", value, "reviewTextCount");
            return (Criteria) this;
        }

        public Criteria andReviewTextCountNotEqualTo(Integer value) {
            addCriterion("review_text_count <>", value, "reviewTextCount");
            return (Criteria) this;
        }

        public Criteria andReviewTextCountGreaterThan(Integer value) {
            addCriterion("review_text_count >", value, "reviewTextCount");
            return (Criteria) this;
        }

        public Criteria andReviewTextCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("review_text_count >=", value, "reviewTextCount");
            return (Criteria) this;
        }

        public Criteria andReviewTextCountLessThan(Integer value) {
            addCriterion("review_text_count <", value, "reviewTextCount");
            return (Criteria) this;
        }

        public Criteria andReviewTextCountLessThanOrEqualTo(Integer value) {
            addCriterion("review_text_count <=", value, "reviewTextCount");
            return (Criteria) this;
        }

        public Criteria andReviewTextCountIn(List<Integer> values) {
            addCriterion("review_text_count in", values, "reviewTextCount");
            return (Criteria) this;
        }

        public Criteria andReviewTextCountNotIn(List<Integer> values) {
            addCriterion("review_text_count not in", values, "reviewTextCount");
            return (Criteria) this;
        }

        public Criteria andReviewTextCountBetween(Integer value1, Integer value2) {
            addCriterion("review_text_count between", value1, value2, "reviewTextCount");
            return (Criteria) this;
        }

        public Criteria andReviewTextCountNotBetween(Integer value1, Integer value2) {
            addCriterion("review_text_count not between", value1, value2, "reviewTextCount");
            return (Criteria) this;
        }

        public Criteria andReviewTextLengthIsNull() {
            addCriterion("review_text_length is null");
            return (Criteria) this;
        }

        public Criteria andReviewTextLengthIsNotNull() {
            addCriterion("review_text_length is not null");
            return (Criteria) this;
        }

        public Criteria andReviewTextLengthEqualTo(Integer value) {
            addCriterion("review_text_length =", value, "reviewTextLength");
            return (Criteria) this;
        }

        public Criteria andReviewTextLengthNotEqualTo(Integer value) {
            addCriterion("review_text_length <>", value, "reviewTextLength");
            return (Criteria) this;
        }

        public Criteria andReviewTextLengthGreaterThan(Integer value) {
            addCriterion("review_text_length >", value, "reviewTextLength");
            return (Criteria) this;
        }

        public Criteria andReviewTextLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("review_text_length >=", value, "reviewTextLength");
            return (Criteria) this;
        }

        public Criteria andReviewTextLengthLessThan(Integer value) {
            addCriterion("review_text_length <", value, "reviewTextLength");
            return (Criteria) this;
        }

        public Criteria andReviewTextLengthLessThanOrEqualTo(Integer value) {
            addCriterion("review_text_length <=", value, "reviewTextLength");
            return (Criteria) this;
        }

        public Criteria andReviewTextLengthIn(List<Integer> values) {
            addCriterion("review_text_length in", values, "reviewTextLength");
            return (Criteria) this;
        }

        public Criteria andReviewTextLengthNotIn(List<Integer> values) {
            addCriterion("review_text_length not in", values, "reviewTextLength");
            return (Criteria) this;
        }

        public Criteria andReviewTextLengthBetween(Integer value1, Integer value2) {
            addCriterion("review_text_length between", value1, value2, "reviewTextLength");
            return (Criteria) this;
        }

        public Criteria andReviewTextLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("review_text_length not between", value1, value2, "reviewTextLength");
            return (Criteria) this;
        }

        public Criteria andKv0IsNull() {
            addCriterion("kv0 is null");
            return (Criteria) this;
        }

        public Criteria andKv0IsNotNull() {
            addCriterion("kv0 is not null");
            return (Criteria) this;
        }

        public Criteria andKv0EqualTo(Integer value) {
            addCriterion("kv0 =", value, "kv0");
            return (Criteria) this;
        }

        public Criteria andKv0NotEqualTo(Integer value) {
            addCriterion("kv0 <>", value, "kv0");
            return (Criteria) this;
        }

        public Criteria andKv0GreaterThan(Integer value) {
            addCriterion("kv0 >", value, "kv0");
            return (Criteria) this;
        }

        public Criteria andKv0GreaterThanOrEqualTo(Integer value) {
            addCriterion("kv0 >=", value, "kv0");
            return (Criteria) this;
        }

        public Criteria andKv0LessThan(Integer value) {
            addCriterion("kv0 <", value, "kv0");
            return (Criteria) this;
        }

        public Criteria andKv0LessThanOrEqualTo(Integer value) {
            addCriterion("kv0 <=", value, "kv0");
            return (Criteria) this;
        }

        public Criteria andKv0In(List<Integer> values) {
            addCriterion("kv0 in", values, "kv0");
            return (Criteria) this;
        }

        public Criteria andKv0NotIn(List<Integer> values) {
            addCriterion("kv0 not in", values, "kv0");
            return (Criteria) this;
        }

        public Criteria andKv0Between(Integer value1, Integer value2) {
            addCriterion("kv0 between", value1, value2, "kv0");
            return (Criteria) this;
        }

        public Criteria andKv0NotBetween(Integer value1, Integer value2) {
            addCriterion("kv0 not between", value1, value2, "kv0");
            return (Criteria) this;
        }

        public Criteria andHarvestPriceIsNull() {
            addCriterion("harvest_price is null");
            return (Criteria) this;
        }

        public Criteria andHarvestPriceIsNotNull() {
            addCriterion("harvest_price is not null");
            return (Criteria) this;
        }

        public Criteria andHarvestPriceEqualTo(Integer value) {
            addCriterion("harvest_price =", value, "harvestPrice");
            return (Criteria) this;
        }

        public Criteria andHarvestPriceNotEqualTo(Integer value) {
            addCriterion("harvest_price <>", value, "harvestPrice");
            return (Criteria) this;
        }

        public Criteria andHarvestPriceGreaterThan(Integer value) {
            addCriterion("harvest_price >", value, "harvestPrice");
            return (Criteria) this;
        }

        public Criteria andHarvestPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("harvest_price >=", value, "harvestPrice");
            return (Criteria) this;
        }

        public Criteria andHarvestPriceLessThan(Integer value) {
            addCriterion("harvest_price <", value, "harvestPrice");
            return (Criteria) this;
        }

        public Criteria andHarvestPriceLessThanOrEqualTo(Integer value) {
            addCriterion("harvest_price <=", value, "harvestPrice");
            return (Criteria) this;
        }

        public Criteria andHarvestPriceIn(List<Integer> values) {
            addCriterion("harvest_price in", values, "harvestPrice");
            return (Criteria) this;
        }

        public Criteria andHarvestPriceNotIn(List<Integer> values) {
            addCriterion("harvest_price not in", values, "harvestPrice");
            return (Criteria) this;
        }

        public Criteria andHarvestPriceBetween(Integer value1, Integer value2) {
            addCriterion("harvest_price between", value1, value2, "harvestPrice");
            return (Criteria) this;
        }

        public Criteria andHarvestPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("harvest_price not between", value1, value2, "harvestPrice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topic_data
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 25 15:32:37 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topic_data
     *
     * @mbggenerated Mon Dec 25 15:32:37 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}