package com.m2m.domain;

import java.util.Date;

public class TopicFragmentLikeHis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_fragment_like_his.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_fragment_like_his.fid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_fragment_like_his.image_id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_fragment_like_his.uid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_fragment_like_his.create_time
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_fragment_like_his.id
     *
     * @return the value of topic_fragment_like_his.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_fragment_like_his.id
     *
     * @param id the value for topic_fragment_like_his.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_fragment_like_his.fid
     *
     * @return the value of topic_fragment_like_his.fid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_fragment_like_his.fid
     *
     * @param fid the value for topic_fragment_like_his.fid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_fragment_like_his.image_id
     *
     * @return the value of topic_fragment_like_his.image_id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_fragment_like_his.image_id
     *
     * @param imageId the value for topic_fragment_like_his.image_id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setImageId(Long imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_fragment_like_his.uid
     *
     * @return the value of topic_fragment_like_his.uid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_fragment_like_his.uid
     *
     * @param uid the value for topic_fragment_like_his.uid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_fragment_like_his.create_time
     *
     * @return the value of topic_fragment_like_his.create_time
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_fragment_like_his.create_time
     *
     * @param createTime the value for topic_fragment_like_his.create_time
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}