package com.m2m.domain;

import java.util.Date;

public class TopicCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_category.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_category.name
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_category.cover_img
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private String coverImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_category.order_num
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_category.create_time
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_category.icon
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_category.id
     *
     * @return the value of topic_category.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_category.id
     *
     * @param id the value for topic_category.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_category.name
     *
     * @return the value of topic_category.name
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_category.name
     *
     * @param name the value for topic_category.name
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_category.cover_img
     *
     * @return the value of topic_category.cover_img
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public String getCoverImg() {
        return coverImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_category.cover_img
     *
     * @param coverImg the value for topic_category.cover_img
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setCoverImg(String coverImg) {
        this.coverImg = coverImg == null ? null : coverImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_category.order_num
     *
     * @return the value of topic_category.order_num
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_category.order_num
     *
     * @param orderNum the value for topic_category.order_num
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_category.create_time
     *
     * @return the value of topic_category.create_time
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_category.create_time
     *
     * @param createTime the value for topic_category.create_time
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_category.icon
     *
     * @return the value of topic_category.icon
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_category.icon
     *
     * @param icon the value for topic_category.icon
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }
}