package com.m2m.domain;

public class UserHobby {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_hobby.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_hobby.uid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_hobby.hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    private Long hobby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_hobby.id
     *
     * @return the value of user_hobby.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_hobby.id
     *
     * @param id the value for user_hobby.id
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_hobby.uid
     *
     * @return the value of user_hobby.uid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_hobby.uid
     *
     * @param uid the value for user_hobby.uid
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_hobby.hobby
     *
     * @return the value of user_hobby.hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public Long getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_hobby.hobby
     *
     * @param hobby the value for user_hobby.hobby
     *
     * @mbggenerated Thu Jan 11 17:51:54 CST 2018
     */
    public void setHobby(Long hobby) {
        this.hobby = hobby;
    }
}